// apps/web-vue/src/features/control/panels/control-timeline-panel.vue
<script setup lang="ts">
import { Grid } from "@styled-system/jsx";
import { ref } from "vue";

import ControlTimelineControls from "@/features/control/panels/timeline/control-timeline-controls.vue";
import ControlTimelineTable from "@/features/control/timeline/timeline-table.vue";

const timelineTableRef = ref<InstanceType<typeof ControlTimelineTable> | null>(null);
</script>

<template>
  <Grid templateRows="1fr auto" h="full">
    <ControlTimelineTable ref="timelineTableRef" />
    <ControlTimelineControls
      :onJumpToCurrent="() => timelineTableRef?.scrollToCurrent()"
    />
  </Grid>
</template>

// apps/web/src/features/control/panels/control-timeline-panel.tsx
import { Grid } from "@chakra-ui/react";
import { useRef } from "react";

import { ControlTimelineTable, type ControlTimelineTableHandle } from "../timeline/timeline-table";
import { ControlTimelineControls } from "./timeline/control-timeline-controls";

export function ControlTimelinePanel() {
  const apiRef = useRef<ControlTimelineTableHandle | null>(null);

  return (
    <Grid templateRows="1fr auto" h="full">
      <ControlTimelineTable apiRef={apiRef} />

      <ControlTimelineControls onJumpToCurrent={() => apiRef.current?.scrollToCurrent()} />
    </Grid>
  );
}
