// apps/web/src/features/extensions/config-panel.tsx
import { Button, EmptyState, HStack, Stack, Text } from "@chakra-ui/react";
import { useSignal } from "@preact/signals-react";
import { useForm, useSelector } from "@tanstack/react-form";
import { getDefaultValues, type RuntimeFormDefinition, toValibotSchema } from "@tgb-form/core";
import { TgbForm } from "@tgb-form/react";
import { type TimelineEvent, TimelineEventType } from "@tgb-resolver/realtime";
import { useEffect, useMemo } from "react";

import type { FloatingPanelHandle } from "@/features/control/floating-panel-model";
import { showModel } from "@/features/shared/show-model";

import { extensionRegistry } from "./base/registry";
import { MediaExtension, type MediaExtensionPayload } from "./media";
import { computeMediaExtensionDuration } from "./media/duration";
import { usePatchExtensionPayload } from "./patch";
import { sharedRendererRegistry } from "./renderers";
import { ScrollerExtension, type ScrollerExtensionPayload } from "./scroller";
import { computeScrollerExtensionDuration } from "./scroller/duration";
import { toTgbFormInstance } from "./tgb-form-instance";

type CustomTimelineEvent = Extract<TimelineEvent, { type: TimelineEventType.CUS }>;

function unwrapRestoredValue(value: unknown): unknown {
  if (!value || typeof value !== "object" || Array.isArray(value)) return value;
  if (!isRecord(value)) return value;
  const record = value;
  if (Object.keys(record).length === 1 && "value" in record)
    return unwrapRestoredValue(record.value);
  return value;
}

function isRecord(value: object): value is Record<string, unknown> {
  return Object.getPrototypeOf(value) === Object.prototype || Object.getPrototypeOf(value) === null;
}

function restoredPayload(payload: Record<string, unknown> | undefined): Record<string, unknown> {
  if (!payload) return {};
  return Object.fromEntries(
    Object.entries(payload).map(([key, value]) => [key, unwrapRestoredValue(value)]),
  );
}

interface ExtensionConfigPanelProps {
  panel: FloatingPanelHandle;
  eventId: number;
}

export function ExtensionConfigPanel({ panel, eventId }: ExtensionConfigPanelProps) {
  const event = showModel.showEvents.value[eventId];

  if (!event || event.type !== TimelineEventType.CUS) {
    return (
      <EmptyState.Root>
        <EmptyState.Content>
          <EmptyState.Title>No configuration available</EmptyState.Title>
          <EmptyState.Description>This event has no extension config.</EmptyState.Description>
        </EmptyState.Content>
      </EmptyState.Root>
    );
  }

  const ext = extensionRegistry.extensionWithExtId(event.payload.extId);
  const configForm = ext?.configForm;

  if (!configForm) {
    return (
      <EmptyState.Root>
        <EmptyState.Content>
          <EmptyState.Title>No configuration available</EmptyState.Title>
          <EmptyState.Description>
            Extension "{event.payload.extId}" has no config form.
          </EmptyState.Description>
        </EmptyState.Content>
      </EmptyState.Root>
    );
  }

  return (
    <ExtensionConfigForm panel={panel} event={event} eventId={eventId} configForm={configForm} />
  );
}

function ExtensionConfigForm({
  panel,
  event,
  eventId,
  configForm,
}: {
  panel: FloatingPanelHandle;
  event: CustomTimelineEvent;
  eventId: number;
  configForm: RuntimeFormDefinition;
}) {
  const patchPayload = usePatchExtensionPayload();
  const error = useSignal<string | null>(null);

  const baseline = useMemo(
    () =>
      ({ ...getDefaultValues(configForm), ...restoredPayload(event.payload.extPayload) }) as Record<
        string,
        unknown
      >,
    [configForm, event],
  );

  const form = useForm({
    defaultValues: baseline,
    validators: {
      onSubmit: toValibotSchema(configForm) as never,
    },
    onSubmit: async ({ value }) => {
      error.value = null;
      panel.setSaving(true);
      try {
        let durationSeconds: number | undefined;
        if (event.payload.extId === MediaExtension.extId) {
          durationSeconds =
            (await computeMediaExtensionDuration(value as MediaExtensionPayload)) ?? undefined;
        } else if (event.payload.extId === ScrollerExtension.extId) {
          durationSeconds = computeScrollerExtensionDuration(value as ScrollerExtensionPayload);
        }
        if (durationSeconds !== undefined) {
          await patchPayload(eventId, event.payload.extId, value, durationSeconds);
        } else {
          await patchPayload(eventId, event.payload.extId, value);
        }
        panel.close(true);
      } catch (err) {
        error.value = err instanceof Error ? err.message : String(err);
      } finally {
        panel.setSaving(false);
      }
    },
  });

  const isDirty = useSelector(
    form.store,
    (state) => JSON.stringify(state.values) !== JSON.stringify(baseline),
  );
  const canSubmit = useSelector(form.store, (state) => state.canSubmit);

  useEffect(() => {
    panel.setDirty(isDirty);
  }, [isDirty, panel]);

  return (
    <Stack gap={4} h="full">
      <TgbForm
        definition={configForm}
        instance={toTgbFormInstance(form)}
        renderers={sharedRendererRegistry}
        style={{ gap: "1rem", display: "flex", flexDirection: "column" }}
      />
      <HStack justify="end">
        <Button variant="outline" onClick={() => void panel.requestClose()}>
          Cancel
        </Button>
        <Button
          disabled={!canSubmit || !isDirty || panel.isSaving.value}
          onClick={() => void form.handleSubmit()}
        >
          Save
        </Button>
      </HStack>
      {error.value && (
        <Text color="fg.error" fontSize="sm">
          {error.value}
        </Text>
      )}
    </Stack>
  );
}

// apps/web/src/features/extensions/config-panel.vue
<script setup lang="ts">
import { css } from "@styled-system/css";
import { button } from "@styled-system/recipes";
import { TimelineEventType } from "@tgb-resolver/contracts";
import type { CustomEvent } from "@tgb-resolver/realtime";
import { computed, ref, useTemplateRef, watch } from "vue";

import type { FloatingPanelHandle } from "@/features/control/floating-panel-types";
import { useShowStore } from "@/stores/show-store";

import ExtensionConfigForm from "./extension-config-form.vue";
import { computeMediaExtensionDuration } from "./media/duration";
import { patchExtensionEvent } from "./patch";
import { useExtensionRegistry } from "./registry";
import { extensionRendererRegistry } from "./renderers";
import { computeScrollerExtensionDuration } from "./scroller/duration";

const props = defineProps<{ panel: FloatingPanelHandle }>();

const registry = useExtensionRegistry();
const showStore = useShowStore();

const params = computed(() => props.panel.props.value as { eventId?: number });

const event = computed<CustomEvent | null>(() => {
  const eventId = params.value.eventId;
  if (eventId == null) return null;
  const candidate = showStore.showEvents[eventId];
  return candidate?.type === TimelineEventType.CUS ? (candidate as CustomEvent) : null;
});

const extension = computed(() =>
  event.value ? registry.extensionWithExtId(event.value.payload.extId) : undefined,
);
const configForm = computed(() => extension.value?.configForm);
// Restored payload values; the form merges them over definition defaults.
const baseline = computed(() => event.value?.payload.extPayload);

const configFormRef = useTemplateRef<InstanceType<typeof ExtensionConfigForm>>("configFormRef");
const saving = ref(false);
const error = ref<string | null>(null);

const stackCss = css({ display: "flex", flexDirection: "column", gap: 4, h: "full" });
const actionsCss = css({ display: "flex", justifyContent: "flex-end", gap: 2 });
const errorCss = css({ color: "fg.error", fontSize: "sm" });

watch(
  () => configFormRef.value?.isDirty() ?? false,
  (isDirty) => props.panel.setDirty(isDirty),
  { immediate: true },
);

async function handleSubmit(values: Record<string, unknown>) {
  const eventId = params.value.eventId;
  const extId = event.value?.payload.extId;
  if (eventId == null || !extId) {
    props.panel.close(true);
    return;
  }
  saving.value = true;
  error.value = null;
  try {
    const durationSeconds =
      extId === "scroller" ? computeScrollerExtensionDuration(values)
      : extId === "media" ? ((await computeMediaExtensionDuration(values)) ?? undefined)
      : undefined;
    await patchExtensionEvent(eventId, extId, values, durationSeconds);
    props.panel.close(true);
  } catch (cause) {
    error.value = cause instanceof Error ? cause.message : String(cause);
  } finally {
    saving.value = false;
  }
}

function cancel() {
  void props.panel.requestClose();
}
</script>

<template>
  <div :class="stackCss">
    <ExtensionConfigForm
      v-if="configForm"
      :key="`${params.eventId ?? 0}:${event?.payload.extId ?? ''}`"
      ref="configFormRef"
      :definition="configForm"
      :baseline="baseline"
      :renderers="extensionRendererRegistry"
      :on-submit="handleSubmit"
    />
    <p v-else :class="errorCss">No configuration available for this event.</p>
    <div :class="actionsCss">
      <button type="button" :class="button({ variant: 'outline' })" @click="cancel">
        Cancel
      </button>
      <button
        type="button"
        :class="button()"
        :disabled="!configFormRef?.canSubmit() || !configFormRef?.isDirty() || saving"
        @click="configFormRef?.submit()"
      >
        Save
      </button>
    </div>
    <p v-if="error" :class="errorCss">{{ error }}</p>
  </div>
</template>
