// apps/web/src/components/control/timeline/CurrentEventIndicator.tsx
import { Box, useToken } from "@chakra-ui/react";
import { keyframes } from "@emotion/react";
import { useComputed } from "@preact/signals-react";
import { type AnimationPlaybackControls, animate } from "motion/react";
import { useEffect, useRef } from "react";

import { playbackSignal } from "@/models/playback-state";

const pulseBorder = keyframes`
  0%, 100% {
    border-color: var(--chakra-colors-border-success);
  }

  50% {
    border-color: var(--chakra-colors-border);
  }
`;

interface CurrentEventIndicatorProps {
  eventId: number;
  durationInSeconds?: number;
}

export function CurrentEventIndicator({ eventId, durationInSeconds }: CurrentEventIndicatorProps) {
  const eventIsCurrent = useComputed(() => playbackSignal.value.currentEventId === eventId);
  const isCurrent = eventIsCurrent.value;
  const [success, error] = useToken("colors", ["green.600", "red.500"]);
  const barRef = useRef<HTMLDivElement>(null);
  const warnRef = useRef<HTMLDivElement>(null);
  const animationRef = useRef<AnimationPlaybackControls[]>([]);

  useEffect(() => {
    const barEl = barRef.current;
    const warnEl = warnRef.current;
    if (!barEl || !warnEl) return;

    animationRef.current.forEach((controls) => {
      controls.stop();
    });
    animationRef.current = [];

    const duration = durationInSeconds ?? 0;

    if (isCurrent) {
      animationRef.current = [
        animate(barEl, { scaleX: [0, 1] }, { duration, ease: "linear" }),
        animate(warnEl, { opacity: [0, 0, 1] }, { duration, ease: "linear" }),
      ];
    } else {
      animationRef.current = [
        animate(barEl, { scaleX: 0 }, { duration: 0 }),
        animate(warnEl, { opacity: 0 }, { duration: 0 }),
      ];
    }

    return () => {
      animationRef.current.forEach((controls) => {
        controls.stop();
      });
    };
  }, [isCurrent, durationInSeconds]);

  return (
    <>
      <Box
        ref={barRef}
        position="absolute"
        top={0}
        left={0}
        h="full"
        w="full"
        transform="scaleX(0)"
        transformOrigin="left"
        backgroundColor={success}
        pointerEvents="none"
        zIndex={0}
      >
        <Box ref={warnRef} position="absolute" inset={0} backgroundColor={error} opacity={0} />
      </Box>
      <Box
        position="absolute"
        inset={0}
        borderWidth={2}
        borderColor={isCurrent ? "border.success" : "transparent"}
        animation={isCurrent ? `${pulseBorder} 1s infinite` : undefined}
        pointerEvents="none"
        zIndex={1}
      />
    </>
  );
}

// apps/web-vue/src/features/control/timeline/current-event-indicator.vue
<script setup lang="ts">
import { Box } from "@styled-system/jsx";
import { type AnimationPlaybackControls, animate } from "motion";
import { computed, onMounted, onUnmounted, ref, watch } from "vue";

import { usePlaybackStore } from "@/features/control/playback-store";

defineOptions({ name: "CurrentEventIndicator" });
const props = defineProps<{ eventId: number; durationInSeconds?: number }>();
const playback = usePlaybackStore();
const bar = ref<HTMLElement>();
const warning = ref<HTMLElement>();
let controls: AnimationPlaybackControls[] = [];
const active = computed(() => playback.currentEventId === props.eventId || playback.state.activeEventIds.includes(props.eventId));
function stop() { controls.forEach((control) => { control.stop(); }); controls = []; }
function run() {
  stop(); if (!active.value || !bar.value || !warning.value) return;
  const duration = props.durationInSeconds ?? 0;
  controls = [animate(bar.value, { scaleX: [0, 1] }, { duration, ease: "linear" }), animate(warning.value, { opacity: [0, 0, 1] }, { duration, ease: "linear" })];
}
watch(active, run); watch(() => props.durationInSeconds, run); onMounted(run); onUnmounted(stop);
</script>
<template><Box position="absolute" inset="0" pointerEvents="none"><Box v-if="active" ref="bar" position="absolute" inset="0" transform="scaleX(0)" transformOrigin="left" bg="green.600"><Box ref="warning" position="absolute" inset="0" bg="red.500" opacity="0" /></Box><Box v-if="active" position="absolute" inset="0" borderWidth="2" borderColor="border.success" animation="pulse" /></Box></template>
