// apps/web/src/features/control/timeline/timeline-event-position.tsx
import { Box } from "@chakra-ui/react";
import { useComputed } from "@preact/signals-react";
import { useCallback } from "react";

import { showModel } from "@/features/shared/show-model";
import { Tooltip } from "@/features/shared/ui/tooltip";

export interface TimelineEventPositionProps {
  eventId: number;
  fallbackPosition: number;
  onSeek: (id: number) => void;
}

export function TimelineEventPosition({
  eventId,
  fallbackPosition,
  onSeek,
}: TimelineEventPositionProps) {
  const position = useComputed(() => {
    const index = showModel.showOrderedIds.value.indexOf(eventId);
    return index < 0 ? fallbackPosition : index + 1;
  });

  const handleClick = useCallback(() => {
    onSeek(eventId);
  }, [eventId, onSeek]);

  return (
    <Tooltip
      content={`Seek to event #${position.value}`}
      openDelay={0}
      positioning={{ placement: "left" }}
    >
      <Box textAlign="end" fontFamily="mono" cursor="pointer" onClick={handleClick}>
        {position.value}
      </Box>
    </Tooltip>
  );
}

// apps/web-vue/src/features/control/timeline/timeline-event-position.vue
<script setup lang="ts">
import { css } from "@styled-system/css";

import Tooltip from "@/features/shared/ui/tooltip.vue";

const props = defineProps<{
  eventId: number;
  position: number;
}>();

const emit = defineEmits<{
  seek: [id: number];
}>();

function handleClick() {
  emit("seek", props.eventId);
}
</script>

<template>
  <Tooltip
    :content="`Seek to event #${position}`"
    :open-delay="0"
    :positioning="{ placement: 'left', flip: false }"
    show-arrow
  >
    <button
      type="button"
      :class="css({ cursor: 'pointer', fontFamily: 'mono', textAlign: 'end' })"
      @click="handleClick"
    >
      {{ position }}
    </button>
  </Tooltip>
</template>
