// apps/web/src/features/control/timeline/timeline-cell-editable.tsx
import { Box, Editable } from "@chakra-ui/react";
import { useSignal } from "@preact/signals-react";
import { type MouseEvent, type ReactNode, useCallback } from "react";

export interface TimelineCellEditableProps {
  value: string;
  displayValue: ReactNode;
  placeholder?: string;
  onBlankCommit?: () => void;
  textAlign?: "start" | "end";
  fontFamily?: string;
  onCommit: (value: string) => void;
}

export function TimelineCellEditable({
  value,
  displayValue,
  placeholder,
  onBlankCommit,
  textAlign = "start",
  fontFamily,
  onCommit,
}: TimelineCellEditableProps) {
  const editing = useSignal(false);
  const draft = useSignal(value);

  const handleDoubleClickPreview = useCallback(
    (event: MouseEvent<HTMLElement>) => {
      event.stopPropagation();
      draft.value = value;
      editing.value = true;
    },
    [draft, editing, value],
  );

  const handleDoubleClickEditable = useCallback((event: MouseEvent<HTMLElement>) => {
    event.stopPropagation();
  }, []);

  const handleValueChange = useCallback(
    ({ value }: { value: string }) => {
      draft.value = value;
    },
    [draft],
  );

  const handleValueCommit = useCallback(
    ({ value }: { value: string }) => {
      if (value.trim().length === 0 && onBlankCommit) onBlankCommit();
      else onCommit(value);
      editing.value = false;
    },
    [editing, onBlankCommit, onCommit],
  );

  const handleValueRevert = useCallback(() => {
    editing.value = false;
  }, [editing]);

  if (!editing.value) {
    return (
      <Box
        px={1}
        py={0.5}
        minH={6}
        borderRadius="sm"
        textAlign={textAlign}
        fontFamily={fontFamily}
        cursor="text"
        overflow="hidden"
        textOverflow="ellipsis"
        whiteSpace="nowrap"
        onDoubleClick={handleDoubleClickPreview}
      >
        {displayValue}
      </Box>
    );
  }

  return (
    <Editable.Root
      defaultEdit
      submitMode="both"
      value={draft.value}
      placeholder={placeholder}
      onDoubleClick={handleDoubleClickEditable}
      onValueChange={handleValueChange}
      onValueCommit={handleValueCommit}
      onValueRevert={handleValueRevert}
    >
      <Editable.Preview
        px={1}
        py={0.5}
        minH={6}
        borderRadius="sm"
        textAlign={textAlign}
        fontFamily={fontFamily}
        cursor="text"
        overflow="hidden"
        textOverflow="ellipsis"
        whiteSpace="nowrap"
      />
      <Editable.Input
        px={1}
        py={0.5}
        minH={6}
        borderRadius="sm"
        textAlign={textAlign}
        fontFamily={fontFamily}
        bg="bg.panel"
        autoFocus
      />
    </Editable.Root>
  );
}

// apps/web-vue/src/features/control/timeline/timeline-cell-editable.vue
<script setup lang="ts">
import {
  EditableArea,
  EditableInput,
  EditablePreview,
  EditableRoot,
} from "@ark-ui/vue";
import { Box } from "@styled-system/jsx";
import { editable } from "@styled-system/recipes";
import { ref, watch } from "vue";

defineOptions({ name: "TimelineCellEditable" });

const props = withDefaults(
  defineProps<{
    value: string;
    displayValue?: string | number;
    placeholder?: string;
    textAlign?: "start" | "end";
    fontFamily?: string;
  }>(),
  {
    displayValue: undefined,
    placeholder: undefined,
    textAlign: "start",
    fontFamily: undefined,
  },
);

const emit = defineEmits<{
  commit: [value: string];
  blankCommit: [];
}>();

const editing = ref(false);
const draft = ref(props.value);

watch(
  () => props.value,
  (v) => {
    draft.value = v;
  },
);

const editableClasses = editable();

function handleDoubleClickPreview(event: MouseEvent) {
  event.stopPropagation();
  draft.value = props.value;
  editing.value = true;
}

function handleValueChange(details: { value: string }) {
  draft.value = details.value;
}

function handleValueCommit(details: { value: string }) {
  if (details.value.trim().length === 0) {
    emit("blankCommit");
  } else {
    emit("commit", details.value);
  }
  editing.value = false;
}

function handleValueRevert() {
  editing.value = false;
}
</script>

<template>
  <Box
    v-if="!editing"
    px="1"
    py="0.5"
    minH="6"
    rounded="sm"
    :textAlign="textAlign"
    :fontFamily="fontFamily"
    cursor="text"
    overflow="hidden"
    textOverflow="ellipsis"
    whiteSpace="nowrap"
    @dblclick="handleDoubleClickPreview"
  >
    {{ displayValue ?? value }}
  </Box>

  <EditableRoot
    v-else
    :defaultEdit="true"
    submitMode="both"
    :value="draft"
    :placeholder="placeholder"
    :class="editableClasses.root"
    @dblclick.stop
    @value-change="handleValueChange"
    @value-commit="handleValueCommit"
    @value-revert="handleValueRevert"
  >
    <EditableArea :class="editableClasses.area">
      <EditablePreview
        :class="editableClasses.preview"
        px="1"
        py="0.5"
        minH="6"
        rounded="sm"
        :textAlign="textAlign"
        :fontFamily="fontFamily"
        cursor="text"
        overflow="hidden"
        textOverflow="ellipsis"
        whiteSpace="nowrap"
      />
      <EditableInput
        :class="editableClasses.input"
        px="1"
        py="0.5"
        minH="6"
        rounded="sm"
        :textAlign="textAlign"
        :fontFamily="fontFamily"
        bg="bg.panel"
      />
    </EditableArea>
  </EditableRoot>
</template>
