// apps/web/src/features/control/timeline/timeline-manual-interaction.tsx
import { IconButton } from "@chakra-ui/react";
import type { TimelineTableItem } from "@tgb-resolver/realtime";
import { Check } from "lucide-react";
import { type MouseEvent, useCallback } from "react";

import { usePatchTimelineEventMutation } from "@/features/control/hooks";
import { Tooltip } from "@/features/shared/ui/tooltip";

export interface ControlTimelineManualInteractionProps {
  payload: TimelineTableItem;
  isNear?: boolean;
}

export function ControlTimelineManualInteraction({
  payload,
  isNear = false,
}: ControlTimelineManualInteractionProps) {
  const patchEvent = usePatchTimelineEventMutation();

  const handleToggle = useCallback(
    (e: MouseEvent<HTMLElement>) => {
      e.stopPropagation();
      void patchEvent.mutateAsync({
        eventId: payload.id,
        requireManualInteraction: !payload.requireManualInteraction,
      });
    },
    [patchEvent.mutateAsync, payload.id, payload.requireManualInteraction],
  );

  if (!isNear) {
    // Keep the toggle column a plain static indicator when not hovered:
    // mounting a Chakra button for every row is wasted work on rapid
    // unmount/remount. Most rows render nothing at all.
    if (!payload.requireManualInteraction) return null;

    return <Check size={14} />;
  }

  return (
    <Tooltip content="Double-click to toggle manual interaction" openDelay={0}>
      <IconButton
        aria-label="Toggle manual interaction"
        variant="ghost"
        minW={0}
        w="full"
        h={6}
        m={1}
        onDoubleClick={handleToggle}
      >
        {payload.requireManualInteraction ? <Check size={14} /> : null}
      </IconButton>
    </Tooltip>
  );
}

// apps/web-vue/src/features/control/timeline/timeline-manual-interaction.vue
<script setup lang="ts">
import { Check } from "@lucide/vue";
import { css, cx } from "@styled-system/css";
import { button, iconButton } from "@styled-system/recipes";
import type { TimelineTableItem } from "@tgb-resolver/realtime";
import { inject, ref } from "vue";

import { usePatchTimelineEventMutation } from "@/features/control/composables/use-show";
import Tooltip from "@/features/shared/ui/tooltip.vue";

import { timelineRowHoverKey } from "./timeline-row-hover";

const props = defineProps<{
  payload: TimelineTableItem;
}>();

const patchEvent = usePatchTimelineEventMutation();
const isNear = inject(timelineRowHoverKey, ref(false));

function toggle(event: MouseEvent) {
  event.stopPropagation();
  patchEvent.mutate({
    eventId: props.payload.id,
    requireManualInteraction: !props.payload.requireManualInteraction,
  });
}
</script>

<template>
  <Check
    v-if="!isNear && payload.requireManualInteraction"
    :size="14"
    aria-hidden
  />
  <Tooltip
    v-else-if="isNear"
    content="Double-click to toggle manual interaction"
    :open-delay="0"
  >
    <button
      type="button"
      aria-label="Toggle manual interaction"
      :class="
        cx(
          button({ variant: 'ghost' }),
          iconButton(),
          css({ minW: 0, w: 'full', h: 6, m: 1, aspectRatio: 'auto' }),
        )
      "
      @dblclick="toggle"
    >
      <Check
        v-if="payload.requireManualInteraction"
        :size="14"
        aria-hidden
      />
    </button>
  </Tooltip>
</template>
