// apps/web/src/features/leaderboard/rank-cell.tsx
import { Table, Text } from "@chakra-ui/react";
import { memo } from "react";

import { useIsBigScreen } from "./leaderboard-provider";

interface RankCellProps {
  rank: number;
}

export const RankCell = memo(({ rank }: RankCellProps) => {
  const isBigScreen = useIsBigScreen().value;

  return (
    <Table.Cell>
      <Text fontFamily="mono" fontSize={isBigScreen ? "3xl" : undefined} textAlign="end">
        {rank}
      </Text>
    </Table.Cell>
  );
});

// apps/web/src/features/leaderboard/cells/rank-cell.vue
<script setup lang="ts">
import { css, cx } from "@styled-system/css";
import { table } from "@styled-system/recipes";
import { computed } from "vue";

import { useLeaderboardStore } from "@/stores/leaderboard-store";

defineProps<{ rank: number }>();

const isBigScreen = computed(() => useLeaderboardStore().isBigScreen);
const cellClass = computed(() =>
  cx(
    table({ size: isBigScreen.value ? "lg" : "sm", variant: "line" }).cell,
    css({
      textAlign: "end",
      fontFamily: "mono",
      fontSize: isBigScreen.value ? "3xl" : undefined,
    }),
  ),
);
</script>

<template>
  <td :class="cellClass">{{ rank }}</td>
</template>
