// apps/web/src/features/assets-manager/assets-toolbar.tsx
import { DataList, HStack, IconButton } from "@chakra-ui/react";
import { Grid, LayoutList } from "lucide-react";

import { assetsManagerModel } from "./assets-manager-model";

export function AssetsToolbar() {
  const viewMode = assetsManagerModel.viewMode.value;
  const entries = assetsManagerModel.entries.value;

  return (
    <HStack justify="space-between" px={4} py={2} borderBottomWidth={1} w="full">
      <DataList.Root orientation="horizontal" size="sm">
        <DataList.Item>
          <DataList.ItemLabel>Assets</DataList.ItemLabel>
          <DataList.ItemValue>{entries.length} items</DataList.ItemValue>
        </DataList.Item>
      </DataList.Root>

      <HStack gap={1}>
        <IconButton
          aria-label="List view"
          size="sm"
          variant={viewMode === "list" ? "solid" : "ghost"}
          onClick={() => assetsManagerModel.setViewMode("list")}
        >
          <LayoutList size={16} />
        </IconButton>
        <IconButton
          aria-label="Grid view"
          size="sm"
          variant={viewMode === "grid" ? "solid" : "ghost"}
          onClick={() => assetsManagerModel.setViewMode("grid")}
        >
          <Grid size={16} />
        </IconButton>
      </HStack>
    </HStack>
  );
}

// apps/web/src/features/assets-manager/assets-toolbar.vue
<script setup lang="ts">
import { Grid, LayoutList } from "@lucide/vue";
import { css, cx } from "@styled-system/css";
import { button, dataList, iconButton } from "@styled-system/recipes";

import { useAssetsManagerStore } from "./assets-manager-store";

const store = useAssetsManagerStore();
const dataListClasses = dataList({ orientation: "horizontal", size: "sm" });
</script>

<template>
  <div
    :class="
      css({
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        px: '4',
        py: '2',
        borderBottomWidth: 1,
        borderColor: 'border',
        w: 'full',
      })
    "
  >
    <div :class="dataListClasses.root">
      <div :class="dataListClasses.item">
        <div :class="dataListClasses.itemLabel">Assets</div>
        <div :class="dataListClasses.itemValue">{{ store.entries.length }} items</div>
      </div>
    </div>

    <div :class="css({ display: 'flex', flexDirection: 'row', alignItems: 'center', gap: '1' })">
      <button
        type="button"
        aria-label="List view"
        :class="
          cx(button({ variant: store.viewMode === 'list' ? 'solid' : 'ghost', size: 'sm' }), iconButton())
        "
        @click="store.setViewMode('list')"
      >
        <LayoutList :size="16" aria-hidden />
      </button>
      <button
        type="button"
        aria-label="Grid view"
        :class="
          cx(button({ variant: store.viewMode === 'grid' ? 'solid' : 'ghost', size: 'sm' }), iconButton())
        "
        @click="store.setViewMode('grid')"
      >
        <Grid :size="16" aria-hidden />
      </button>
    </div>
  </div>
</template>
