// apps/web/src/features/assets-manager/assets-grid-view.tsx
import { Box, Grid, Image, Text } from "@chakra-ui/react";
import { File, Folder } from "lucide-react";
import { useRef, useState } from "react";

import { toaster } from "@/features/shared/ui/toaster";

import { assetsInteractionModel, INTERNAL_DRAG_MIME } from "./assets-interaction-model";
import { assetsManagerModel } from "./assets-manager-model";
import { ContextMenuOverlay } from "./context-menu-overlay";
import { useEntryContextMenu } from "./use-entry-context-menu";
import { type Rect, useRubberBandSelect } from "./use-rubber-band-select";

const API_URL = import.meta.env.VITE_API_URL ?? "http://localhost:5001";

export function AssetsGridView() {
  const entries = assetsManagerModel.entries.value;
  const selectedIds = assetsManagerModel.selectedIds.value;
  const containerRef = useRef<HTMLDivElement>(null);
  const contextMenu = useEntryContextMenu();

  const { selectionRect, containerHandlers } = useRubberBandSelect(containerRef, (ids, mod) => {
    if (mod) {
      const next = new Set(assetsManagerModel.selectedIds.value);
      for (const id of ids) next.add(id);
      assetsManagerModel.selectedIds.value = next;
    } else {
      assetsManagerModel.selectedIds.value = new Set(ids);
    }
  });

  function handleContainerClick(e: React.MouseEvent) {
    if ((e.target as HTMLElement).closest("[data-context-menu]")) return;
    if (contextMenu.state.target) return;
    const target = e.target as HTMLElement;
    if (target.closest("[data-entry-id]")) return;
    assetsManagerModel.clearSelection();
  }

  function handleEntryClick(e: React.MouseEvent, index: number) {
    assetsManagerModel.handleEntryClick(
      { metaKey: e.metaKey, ctrlKey: e.ctrlKey, shiftKey: e.shiftKey },
      index,
    );
  }

  function handleDoubleClick(entry: { id: string; isDirectory: boolean }) {
    if (entry.isDirectory) {
      assetsManagerModel.selectEntry(entry.id);
    } else {
      window.open(`${API_URL}/assets/${entry.id}`, "_blank");
    }
  }

  function handleDropError(error: unknown): void {
    toaster.create({
      title: "Move assets",
      description: error instanceof Error ? error.message : String(error),
      type: "error",
    });
  }

  return (
    <Box
      ref={containerRef}
      overflowY="auto"
      h="full"
      userSelect="none"
      onClick={handleContainerClick}
      onContextMenu={(e) => {
        const target = e.target as HTMLElement;
        if (!target.closest("[data-entry-id]")) {
          contextMenu.openForContainer(e);
        }
      }}
      onPointerDown={(e) => {
        if ((e.target as HTMLElement).closest("[data-context-menu]")) return;
        assetsManagerModel.focusedPanel.value = "content";
        containerHandlers.onPointerDown(e);
      }}
      onPointerMove={containerHandlers.onPointerMove}
      onPointerUp={containerHandlers.onPointerUp}
      onClickCapture={(e) => {
        if ((e.target as HTMLElement).closest("[data-context-menu]")) return;
        containerHandlers.onClickCapture(e);
      }}
      tabIndex={-1}
      onKeyDown={(e) => {
        if (e.key === "Escape") assetsManagerModel.clearSelection();
      }}
      onDragOver={(e) => {
        if (!assetsInteractionModel.isInternalDragData(e.dataTransfer)) return;
        e.preventDefault();
        const effect: "copy" | "move" = e.altKey ? "copy" : "move";
        assetsInteractionModel.setDragEffect(effect);
        e.dataTransfer.dropEffect = effect;
      }}
      onDrop={(e) => {
        if (!assetsInteractionModel.isInternalDragData(e.dataTransfer)) return;
        e.preventDefault();
        const effect: "copy" | "move" = e.altKey ? "copy" : "move";
        void assetsInteractionModel
          .dropInto(assetsManagerModel.selectedEntryId.value, effect)
          .catch(handleDropError);
      }}
    >
      {entries.length === 0 ? (
        <Box display="flex" alignItems="center" justifyContent="center" h="full">
          <Text color="fg.muted">Empty</Text>
        </Box>
      ) : (
        <Grid templateColumns="repeat(auto-fill, minmax(200px, 1fr))" gap={4} p={4}>
          {entries.map((entry, index) => (
            <EntryCard
              key={entry.id}
              entry={entry}
              isSelected={selectedIds.has(entry.id)}
              onContextMenu={(e) => {
                if (!selectedIds.has(entry.id)) {
                  assetsManagerModel.selectedIds.value = new Set([entry.id]);
                }
                contextMenu.openForEntry(e, {
                  id: entry.id,
                  name: entry.name,
                  isDirectory: entry.isDirectory,
                });
              }}
              onDragStart={(e) => {
                const effect: "copy" | "move" = e.altKey ? "copy" : "move";
                const dragIds = assetsInteractionModel.beginDrag(entry.id, effect);
                e.dataTransfer.effectAllowed = "copyMove";
                e.dataTransfer.setData(INTERNAL_DRAG_MIME, JSON.stringify(dragIds));
              }}
              onDragEnd={() => {
                assetsInteractionModel.clearDrag();
              }}
              onDragOver={
                entry.isDirectory
                  ? (e) => {
                      if (!assetsInteractionModel.isInternalDragData(e.dataTransfer)) return;
                      e.preventDefault();
                      const effect: "copy" | "move" = e.altKey ? "copy" : "move";
                      assetsInteractionModel.setDragEffect(effect);
                      e.dataTransfer.dropEffect = effect;
                    }
                  : undefined
              }
              onDrop={
                entry.isDirectory
                  ? (e) => {
                      if (!assetsInteractionModel.isInternalDragData(e.dataTransfer)) return;
                      e.preventDefault();
                      e.stopPropagation();
                      const effect: "copy" | "move" = e.altKey ? "copy" : "move";
                      void assetsInteractionModel.dropInto(entry.id, effect).catch(handleDropError);
                    }
                  : undefined
              }
              onClick={(e) => handleEntryClick(e, index)}
              onDoubleClick={() => handleDoubleClick(entry)}
            />
          ))}
        </Grid>
      )}
      {selectionRect && <SelectionRectOverlay rect={selectionRect} />}
      <ContextMenuOverlay state={contextMenu.state} onClose={() => contextMenu.close()} />
    </Box>
  );
}

function EntryCard({
  entry,
  isSelected,
  onContextMenu,
  onClick,
  onDoubleClick,
  onDragStart,
  onDragEnd,
  onDragOver,
  onDrop,
}: {
  entry: {
    id: string;
    name: string;
    isDirectory: boolean;
    contentType?: string;
    sizeBytes?: number;
  };
  isSelected: boolean;
  onContextMenu: (e: React.MouseEvent) => void;
  onClick: (e: React.MouseEvent) => void;
  onDoubleClick: () => void;
  onDragStart: (e: React.DragEvent) => void;
  onDragEnd: () => void;
  onDragOver?: (e: React.DragEvent) => void;
  onDrop?: (e: React.DragEvent) => void;
}) {
  const [imgError, setImgError] = useState(false);
  const isImage = !entry.isDirectory && entry.contentType?.startsWith("image/");

  return (
    <Box
      data-entry-id={entry.id}
      draggable
      borderWidth={2}
      borderColor={isSelected ? "colorPalette.border" : "border"}
      borderRadius="md"
      overflow="hidden"
      cursor="pointer"
      _hover={{ shadow: "md" }}
      onClick={(e) => {
        e.stopPropagation();
        onClick(e);
      }}
      onDoubleClick={(e) => {
        e.stopPropagation();
        onDoubleClick();
      }}
      onContextMenu={(e) => {
        e.stopPropagation();
        onContextMenu(e);
      }}
      onDragStart={onDragStart}
      onDragEnd={onDragEnd}
      onDragOver={onDragOver}
      onDrop={onDrop}
    >
      <Box h={32} display="flex" alignItems="center" justifyContent="center" bg="bg.subtle">
        {entry.isDirectory ? (
          <Folder size={40} />
        ) : isImage && !imgError ? (
          <Image
            src={`${API_URL}/assets/${entry.id}`}
            alt={entry.name}
            boxSize="full"
            objectFit="contain"
            onError={() => setImgError(true)}
          />
        ) : (
          <File size={40} />
        )}
      </Box>
      <Box p={3}>
        <Text fontSize="sm" fontWeight="medium" wordBreak="break-all">
          {entry.name}
        </Text>
        {!entry.isDirectory && (
          <Text fontSize="xs" color="fg.muted" mt={1}>
            {formatSize(entry.sizeBytes ?? 0)}
          </Text>
        )}
      </Box>
    </Box>
  );
}

function SelectionRectOverlay({ rect }: { rect: Rect }) {
  return (
    <Box
      position="fixed"
      left={rect.left}
      top={rect.top}
      width={rect.width}
      height={rect.height}
      bg="colorPalette.solid/10"
      borderWidth={1}
      borderColor="colorPalette.solid"
      pointerEvents="none"
      zIndex="floating"
    />
  );
}

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(0)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

// apps/web/src/features/assets-manager/assets-grid-view.vue
<script setup lang="ts">
import { css } from "@styled-system/css";
import { useTemplateRef } from "vue";

import { toaster } from "@/features/shared/ui/toaster";

import { INTERNAL_DRAG_MIME, useAssetsInteractionStore } from "./assets-interaction-store";
import { useAssetsManagerStore } from "./assets-manager-store";
import ContextMenuOverlay from "./context-menu-overlay.vue";
import EntryCard from "./entry-card.vue";
import type { FsEntry } from "./types";
import { useEntryContextMenu } from "./use-entry-context-menu";
import { useRubberBandSelect } from "./use-rubber-band-select";

const store = useAssetsManagerStore();
const interactionStore = useAssetsInteractionStore();
const contextMenu = useEntryContextMenu();
const containerRef = useTemplateRef<HTMLElement>("containerRef");

const API_URL = import.meta.env.VITE_API_URL ?? "http://localhost:5001";

const { selectionRect, containerHandlers } = useRubberBandSelect(containerRef, (ids, mod) => {
  if (mod) {
    const next = new Set(store.selectedIds);
    for (const id of ids) next.add(id);
    store.selectedIds = next;
  } else {
    store.selectedIds = new Set(ids);
  }
});

function handleContainerClick(e: MouseEvent) {
  const target = e.target as HTMLElement;
  if (target.closest("[data-context-menu]")) return;
  if (contextMenu.state.value.isOpen) return;
  if (target.closest("[data-entry-id]")) return;
  store.clearSelection();
}

function handleEntryClick(e: MouseEvent, index: number) {
  store.handleEntryClick(e, index);
}

function handleDoubleClick(entry: FsEntry) {
  if (entry.isDirectory) {
    store.selectEntry(entry.id);
  } else {
    window.open(`${API_URL}/assets/${entry.id}`, "_blank");
  }
}

function handleDropError(error: unknown): void {
  toaster.create({
    title: "Move assets",
    description: error instanceof Error ? error.message : String(error),
    type: "error",
  });
}
</script>

<template>
  <div
    ref="containerRef"
    role="listbox"
    aria-multiselectable="true"
    tabindex="-1"
    :class="css({ overflowY: 'auto', h: 'full', userSelect: 'none' })"
    @click="handleContainerClick"
    @contextmenu="
      (e) => {
        const target = e.target as HTMLElement;
        if (!target.closest('[data-entry-id]')) {
          contextMenu.openForContainer(e);
        }
      }
    "
    @pointerdown="
      (e) => {
        const target = e.target as HTMLElement;
        if (target.closest('[data-context-menu]')) return;
        store.focusedPanel = 'content';
        containerHandlers.onPointerDown(e);
      }
    "
    @pointermove="containerHandlers.onPointerMove"
    @pointerup="containerHandlers.onPointerUp"
    @click.capture="
      (e) => {
        const target = e.target as HTMLElement;
        if (target.closest('[data-context-menu]')) return;
        containerHandlers.onClickCapture(e);
      }
    "
    @keydown.esc="store.clearSelection"
    @dragover="
      (e) => {
        if (!interactionStore.isInternalDragData(e.dataTransfer)) return;
        e.preventDefault();
        const effect = e.altKey ? 'copy' : 'move';
        interactionStore.setDragEffect(effect);
        if (e.dataTransfer) e.dataTransfer.dropEffect = effect;
      }
    "
    @drop="
      async (e) => {
        if (!interactionStore.isInternalDragData(e.dataTransfer)) return;
        e.preventDefault();
        const effect = e.altKey ? 'copy' : 'move';
        try {
          await interactionStore.dropInto(store.selectedEntryId, effect);
        } catch (err) {
          handleDropError(err);
        }
      }
    "
  >
    <div
      v-if="store.entries.length === 0"
      :class="css({ display: 'flex', alignItems: 'center', justifyContent: 'center', h: 'full', color: 'fg.muted' })"
    >
      Empty
    </div>

    <div
      v-else
      :class="
        css({
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
          gap: 4,
          p: 4,
        })
      "
    >
      <EntryCard
        v-for="(entry, index) in store.entries"
        :key="entry.id"
        :entry="entry"
        :is-selected="store.selectedIds.has(entry.id)"
        @click="handleEntryClick($event, index)"
        @dblclick="handleDoubleClick(entry)"
        @contextmenu="
          (e) => {
            if (!store.selectedIds.has(entry.id)) {
              store.selectedIds = new Set([entry.id]);
            }
            contextMenu.openForEntry(e, {
              id: entry.id,
              name: entry.name,
              isDirectory: entry.isDirectory,
            });
          }
        "
        @dragstart="
          (e) => {
            const effect = e.altKey ? 'copy' : 'move';
            const dragIds = interactionStore.beginDrag(entry.id, effect);
            if (e.dataTransfer) {
              e.dataTransfer.effectAllowed = 'copyMove';
              e.dataTransfer.setData(INTERNAL_DRAG_MIME, JSON.stringify(dragIds));
            }
          }
        "
        @dragend="interactionStore.clearDrag"
        @dragover="
          (e) => {
            if (!interactionStore.isInternalDragData(e.dataTransfer)) return;
            e.preventDefault();
            const effect = e.altKey ? 'copy' : 'move';
            interactionStore.setDragEffect(effect);
            if (e.dataTransfer) e.dataTransfer.dropEffect = effect;
          }
        "
        @drop="
          async (e) => {
            if (!interactionStore.isInternalDragData(e.dataTransfer)) return;
            e.preventDefault();
            e.stopPropagation();
            const effect = e.altKey ? 'copy' : 'move';
            try {
              await interactionStore.dropInto(entry.id, effect);
            } catch (err) {
              handleDropError(err);
            }
          }
        "
      />
    </div>

    <div
      v-if="selectionRect"
      :class="css({
        position: 'fixed',
        left: `${selectionRect.left}px`,
        top: `${selectionRect.top}px`,
        width: `${selectionRect.width}px`,
        height: `${selectionRect.height}px`,
        bg: 'colorPalette.solid/10',
        borderWidth: 1,
        borderColor: 'colorPalette.solid',
        pointerEvents: 'none',
      })"
    />

    <ContextMenuOverlay :state="contextMenu.state.value" @close="contextMenu.close" />
  </div>
</template>
