// apps/web-vue/src/features/shared/ui/toaster.vue
<script setup lang="ts">
import { Toast } from "@ark-ui/vue";
import { X } from "@lucide/vue";
import { Stack } from "@styled-system/jsx";
import { toast } from "@styled-system/recipes";

import Spinner from "./spinner.vue";
import { toaster } from "./toaster";

const toastClasses = toast();
</script>

<template>
  <Toaster :toaster="toaster">
    <template #default="t">
      <Toast.Root :class="toastClasses.root">
        <Spinner v-if="t.type === 'loading'" size="sm" label="" aria-hidden="true" />
        <Stack gap="1" flex="1" maxWidth="100%">
          <Toast.Title v-if="t.title" :class="toastClasses.title">{{ t.title }}</Toast.Title>
          <Toast.Description v-if="t.description" :class="toastClasses.description">{{
            t.description
          }}</Toast.Description>
        </Stack>
        <Toast.ActionTrigger v-if="t.action">{{ t.action.label }}</Toast.ActionTrigger>
        <Toast.CloseTrigger
          v-if="t.closable"
          :class="toastClasses.closeTrigger"
          aria-label="Close toast"
        >
          <X aria-hidden />
        </Toast.CloseTrigger>
      </Toast.Root>
    </template>
  </Toaster>
</template>

// apps/web/src/features/shared/ui/toaster.tsx
"use client";

import {
  Toaster as ChakraToaster,
  createToaster,
  Portal,
  Spinner,
  Stack,
  Toast,
} from "@chakra-ui/react";

export const toaster = createToaster({
  placement: "bottom-end",
  pauseOnPageIdle: true,
});

export const Toaster = () => {
  return (
    <Portal>
      <ChakraToaster toaster={toaster} insetInline={{ mdDown: "4" }}>
        {(toast) => (
          <Toast.Root width={{ md: "sm" }}>
            {toast.type === "loading" ? (
              <Spinner size="sm" color="blue.solid" />
            ) : (
              <Toast.Indicator />
            )}
            <Stack gap="1" flex="1" maxWidth="100%">
              {toast.title && <Toast.Title>{toast.title}</Toast.Title>}
              {toast.description && <Toast.Description>{toast.description}</Toast.Description>}
            </Stack>
            {toast.action && <Toast.ActionTrigger>{toast.action.label}</Toast.ActionTrigger>}
            {toast.closable && <Toast.CloseTrigger />}
          </Toast.Root>
        )}
      </ChakraToaster>
    </Portal>
  );
};
