// apps/web-vue/src/features/control/timeline/timeline-table-item.vue
<script setup lang="ts">
import { GripVertical } from "@lucide/vue";
import { Box } from "@styled-system/jsx";
import { TimelineEventType } from "@tgb-resolver/contracts";
import type { TimelineTableItem } from "@tgb-resolver/realtime";
import { computed, ref } from "vue";

import { useFloatingPanelStore } from "@/features/control/floating-panel-store";
import { FloatingPanelType } from "@/features/control/floating-panel-types";
import { extensionRegistry } from "@/features/extensions/registry";
import GridTableRow from "@/features/shared/ui/grid-table-row.vue";
import IconButton from "@/features/shared/ui/icon-button.vue";
import { useShowStore } from "@/stores/show-store";

import CurrentEventIndicator from "./current-event-indicator.vue";
import TimelineAddButtons from "./timeline-add-buttons.vue";
import TimelineCustomNameEditable from "./timeline-custom-name-editable.vue";
import TimelineEventPosition from "./timeline-event-position.vue";
import TimelineManualInteraction from "./timeline-manual-interaction.vue";
import TimelineNumberEditable from "./timeline-number-editable.vue";
import {
  timelineTableGridTemplateColumns,
  timelineTableGridTemplateColumnsStatic,
} from "./timeline-table-column-config";

const props = defineProps<{
  payload: TimelineTableItem;
  isLive?: boolean;
}>();

const emit = defineEmits<{
  seek: [id: number];
  contextmenu: [event: MouseEvent, payload: TimelineTableItem];
}>();

const showStore = useShowStore();
const floatingPanelStore = useFloatingPanelStore();
const isNear = ref(false);

const isReorderable = computed(
  () => props.payload.type === TimelineEventType.CUS && !props.isLive,
);

const templateColumns = computed(() =>
  props.isLive
    ? timelineTableGridTemplateColumnsStatic
    : timelineTableGridTemplateColumns,
);

const type = computed(() =>
  props.payload.type === TimelineEventType.CUS
    ? extensionRegistry.extensionWithExtId(props.payload.extId ?? "")?.shortName ?? "UNK"
    : props.payload.type,
);

const position = computed(
  () =>
    showStore.showOrderedIds.indexOf(props.payload.id) + 1 ||
    props.payload.position,
);

function resolveDisplayName(payload: Pick<TimelineTableItem, "customName" | "placeholderName">) {
  return payload.customName && payload.customName.trim().length > 0
    ? payload.customName
    : payload.placeholderName;
}

function handleDoubleClick() {
  if (props.payload.type === TimelineEventType.CUS) {
    floatingPanelStore.openFloatingPanel(
      FloatingPanelType.ExtensionConfig,
      `Edit Event #${position.value}`,
      { eventId: props.payload.id },
    );
  }
}
</script>

<template>
  <Box
    w="full"
    minH="8"
    position="relative"
    borderBottomWidth="1"
    borderColor="border"
    :data-event-id="payload.id"
    :data-current="isLive || undefined"
    @pointerenter="isNear = true"
    @pointerleave="isNear = false"
    @contextmenu="emit('contextmenu', $event, payload)"
    @dblclick="handleDoubleClick"
  >
    <CurrentEventIndicator
      :event-id="payload.id"
      :duration-in-seconds="payload.durationSeconds"
    />

    <GridTableRow :templateColumns="templateColumns" px="2">
      <TimelineEventPosition
        :event-id="payload.id"
        :position="position"
        @seek="emit('seek', $event)"
      />

      <Box fontFamily="mono" textTransform="uppercase">
        {{ type }}
      </Box>

      <Box minW="0">
        <TimelineCustomNameEditable
          v-if="!isLive"
          :payload="payload"
        />
        <Box v-else>
          {{ resolveDisplayName(payload) }}
        </Box>
      </Box>

      <Box fontFamily="mono" overflow="hidden" textOverflow="ellipsis" whiteSpace="nowrap">
        {{ payload.problem ?? "" }}
        <template v-if="payload.problem && payload.newProblemScore !== undefined">
          ({{ payload.newProblemScore }})
        </template>
      </Box>

      <Box textAlign="end" fontFamily="mono">
        {{ payload.newTotalScore ?? "" }}
      </Box>

      <Box textAlign="end" fontFamily="mono">
        {{ payload.newRank ?? "" }}
      </Box>

      <TimelineNumberEditable
        v-if="!isLive"
        :payload="payload"
        field="durationSeconds"
      />
      <Box v-else textAlign="end" fontFamily="mono">
        {{ payload.durationSeconds ?? "" }}
      </Box>

      <TimelineNumberEditable
        v-if="!isLive"
        :payload="payload"
        field="triggerOffsetSeconds"
      />
      <Box v-else textAlign="end" fontFamily="mono">
        {{
          payload.triggerOffsetSeconds != null && payload.triggerOffsetSeconds > 0
            ? `+${payload.triggerOffsetSeconds}`
            : ""
        }}
      </Box>

      <Box display="flex" alignItems="center" justifyContent="center" h="6">
        <TimelineManualInteraction
          :payload="payload"
          :is-near="isNear"
        />
      </Box>

      <Box
        v-if="!isLive"
        display="flex"
        alignItems="center"
        justifyContent="center"
        h="full"
      >
        <IconButton
          ariaLabel="Drag to reorder event"
          size="2xs"
          variant="ghost"
          :disabled="!isReorderable"
          :cursor="isReorderable ? 'grab' : 'not-allowed'"
          color="fg.muted"
          :_hover="{ color: 'fg' }"
        >
          <GripVertical :size="14" aria-hidden />
        </IconButton>
      </Box>
    </GridTableRow>

    <TimelineAddButtons
      v-if="!isLive"
      :payload="payload"
      :is-near="isNear"
    />
  </Box>
</template>

// apps/web/src/components/control/timeline/timeline-table-item.tsx
import { Box, DataList, Editable, Grid, type GridProps } from "@chakra-ui/react";
import type { TimelineTableItem } from "@tgb-resolver/realtime";
import { Check } from "lucide-react";
import { memo, useEffect, useState } from "react";

import { Tooltip } from "@/components/ui/tooltip";
import { useRenameControlEventMutation } from "@/features/control/hooks";

import { CurrentEventIndicator } from "./CurrentEventIndicator";
import { TIMELINE_TABLE_GRID_TEMPLATE_COLUMNS } from "./timeline-table-column.config";

function resolveDisplayName(payload: Pick<TimelineTableItem, "customName" | "placeholderName">) {
  return payload.customName && payload.customName.trim().length > 0
    ? payload.customName
    : payload.placeholderName;
}

interface ControlTimelineTableItemProps {
  payload: TimelineTableItem;
  isLive: boolean;
  onSeek: (id: number) => void;
}

export const ControlTimelineTableItem = memo(
  ({ payload, isLive, onSeek }: ControlTimelineTableItemProps) => {
    const durationInSeconds = payload.durationSeconds;

    return (
      <Box
        w="full"
        h={8}
        position="relative"
        borderBottomColor="border"
        overflow="hidden"
        data-event-id={payload.id}
      >
        <CurrentEventIndicator eventId={payload.id} durationInSeconds={durationInSeconds} />

        <ControlTimelineTableGridRow>
          <Tooltip
            content={`Seek to #${payload.id}`}
            openDelay={0}
            positioning={{ placement: "left" }}
          >
            <Box
              textAlign="end"
              fontFamily="mono"
              cursor="pointer"
              onClick={() => onSeek(payload.id)}
            >
              {payload.id}
            </Box>
          </Tooltip>
          <Box fontFamily="mono" textTransform="uppercase">
            {payload.type}
          </Box>
          <Box minW={0}>
            {!isLive ? (
              <ControlTimelineEventCustomNameEditable payload={payload} />
            ) : (
              <Box>{resolveDisplayName(payload)}</Box>
            )}
          </Box>
          <Box fontFamily="mono" overflow="hidden" textOverflow="ellipsis">
            {payload.problem ? `${payload.problem}` : ""}
            {payload.newProblemScore !== undefined ? ` (${payload.newProblemScore})` : ""}
          </Box>
          <Box textAlign="end" fontFamily="mono">
            {payload.newTotalScore}
          </Box>
          <Box textAlign="end" fontFamily="mono">
            {payload.newRank}
          </Box>
          <Box textAlign="end" fontFamily="mono">
            {payload.durationSeconds}
          </Box>
          <Box textAlign="end" fontFamily="mono">
            {payload.triggerOffsetSeconds !== undefined && payload.triggerOffsetSeconds >= 0
              ? `+${payload.triggerOffsetSeconds}`
              : payload.triggerOffsetSeconds}
          </Box>
          <Box>{payload.requireManualInteraction ? <Check size={18} /> : null}</Box>
        </ControlTimelineTableGridRow>
      </Box>
    );
  },
);

export function ControlTimelineTableHeader() {
  return (
    <ControlTimelineTableGridRow h="auto" bg="bg.subtle" py={2}>
      <Tooltip content="Event ID" openDelay={0}>
        <Box textAlign="end">No.</Box>
      </Tooltip>

      <Tooltip content={<ControlTimelineEventTypeHeaderTooltip />} openDelay={0}>
        <Box>Type</Box>
      </Tooltip>

      <Tooltip content="Name for this event. Double-click to customize." openDelay={0}>
        <Box>Name</Box>
      </Tooltip>

      <Tooltip content="Problem name and score for this resolve event." openDelay={0}>
        <Box>Prob.</Box>
      </Tooltip>

      <Tooltip content="New total team score after this resolve event." openDelay={0}>
        <Box textAlign="end">NScore</Box>
      </Tooltip>

      <Tooltip content="New rank after this resolve event." openDelay={0}>
        <Box textAlign="end">NRank</Box>
      </Tooltip>

      <Tooltip content="Duration in seconds. Cannot be negative." openDelay={0}>
        <Box textAlign="end">Dur.</Box>
      </Tooltip>

      <Tooltip
        content="Trigger offset from the start of previous event in seconds. Can be negative."
        openDelay={0}
      >
        <Box textAlign="end">Trig. Off.</Box>
      </Tooltip>

      <Tooltip content="Whether this event requires manual interaction to proceed." openDelay={0}>
        <Box>Man.?</Box>
      </Tooltip>
    </ControlTimelineTableGridRow>
  );
}

function ControlTimelineTableGridRow({ children, ...props }: GridProps) {
  return (
    <Grid
      w="full"
      templateColumns={TIMELINE_TABLE_GRID_TEMPLATE_COLUMNS}
      gapX={2}
      h={8}
      alignItems="center"
      css={{
        "& > *": {
          zIndex: 10,
          alignItems: "center",
        },
      }}
      {...props}
    >
      {children}
    </Grid>
  );
}

function ControlTimelineEventTypeHeaderTooltip() {
  return (
    <DataList.Root>
      <DataList.Item>
        <DataList.ItemLabel>RES</DataList.ItemLabel>
        <DataList.ItemValue>Contestant Resolve</DataList.ItemValue>
      </DataList.Item>

      <DataList.Item>
        <DataList.ItemLabel>SFX</DataList.ItemLabel>
        <DataList.ItemValue>Play SFX</DataList.ItemValue>
      </DataList.Item>

      <DataList.Item>
        <DataList.ItemLabel>IMG</DataList.ItemLabel>
        <DataList.ItemValue>Show Image</DataList.ItemValue>
      </DataList.Item>
    </DataList.Root>
  );
}

interface ControlTimelineEventCustomNameEditableProps {
  payload: TimelineTableItem;
}

function ControlTimelineEventCustomNameEditable({
  payload,
}: ControlTimelineEventCustomNameEditableProps) {
  const renameEvent = useRenameControlEventMutation();

  useEffect(() => {
    setDraftName(payload.customName ?? "");
  }, [payload.customName]);

  const [draftName, setDraftName] = useState(payload.customName ?? "");

  async function commitName(nextValue: string) {
    const normalizedNextValue = nextValue.trim();
    const normalizedCurrentValue = (payload.customName ?? "").trim();

    if (normalizedNextValue === normalizedCurrentValue) {
      setDraftName(payload.customName ?? "");
      return;
    }

    await renameEvent.mutateAsync({
      eventId: payload.id,
      type: payload.type,
      customName: normalizedNextValue,
    });
  }

  return (
    <Editable.Root
      activationMode="dblclick"
      submitMode="both"
      value={draftName}
      placeholder={payload.placeholderName}
      onValueChange={({ value }) => setDraftName(value)}
      onValueCommit={({ value }) => {
        void commitName(value);
      }}
      onValueRevert={() => setDraftName(payload.customName ?? "")}
    >
      <Editable.Preview
        px={1}
        py={0.5}
        minH={6}
        borderRadius="sm"
        cursor="text"
        overflow="hidden"
        textOverflow="ellipsis"
        whiteSpace="nowrap"
      />
      <Editable.Input px={1} py={0.5} minH={6} borderRadius="sm" bg="bg.panel" autoFocus />
    </Editable.Root>
  );
}
