// apps/web/src/features/leaderboard/leaderboard-row.tsx
import { Table, useToken } from "@chakra-ui/react";
import { useSignalEffect } from "@preact/signals-react";
import type { LeaderboardEntry } from "@tgb-resolver/realtime";
import { motion, type Variants } from "motion/react";
import { memo, useMemo, useRef } from "react";

import { leaderboardModel } from "@/features/leaderboard/leaderboard-model";
import { animateScrollIntoView } from "@/features/leaderboard/utils/scroll";
import { useColorMode } from "@/features/shared/ui/color-mode";
import { entryEqual } from "@/lib/leaderboard-comparators";

import { TgbResolverEasings } from "../shared/anim/easings";
import { PenaltyCell, RankCell, ScoreCell, SubmissionTimeCell, UsernameCell } from "./cells";
import { ProblemCell } from "./problem-cell";

// TODO: adjust animation timings to be relative to whole event's duration
// TODO: submission count to show a contestant's effort on a problem, and we'll show the verdict on those individual attempt also
// TODO: rank number anim
// TODO: update with a pending, pending-active state, as currently it it's turning "unexpectedly" from Unknown to Pending
// on PRE-RES, which is kinda bad on the UX side of things

const MotionRow = motion.create(Table.Row);

interface LeaderboardRowProps {
  data: LeaderboardEntry;
  isCurrentResolved: boolean;
}

export const LeaderboardRow = memo(
  ({ data, isCurrentResolved }: LeaderboardRowProps) => {
    const [normalBg, darkBg, lightBg] = useToken("colors", ["bg", "yellow.700", "yellow.300"]);
    const { colorMode } = useColorMode();

    const variants: Variants = useMemo(
      () => ({
        dark: { backgroundColor: normalBg },
        darkCurrent: { backgroundColor: darkBg },
        light: { backgroundColor: normalBg },
        lightCurrent: { backgroundColor: lightBg },
      }),
      [normalBg, darkBg, lightBg],
    );

    const currentVariant = useMemo(() => {
      if (colorMode === "dark") {
        return isCurrentResolved ? "darkCurrent" : "dark";
      } else {
        return isCurrentResolved ? "lightCurrent" : "light";
      }
    }, [colorMode, isCurrentResolved]);

    const ref = useRef<HTMLTableRowElement>(null);

    useSignalEffect(() => {
      const targetId = leaderboardModel.currentBottomView.value;
      if (targetId !== data.userId) return;

      requestAnimationFrame(() => {
        if (!ref.current) return;

        let parent: HTMLElement | null = ref.current.parentElement;
        while (parent) {
          const style = getComputedStyle(parent);
          if (
            style.overflow === "auto" ||
            style.overflow === "scroll" ||
            style.overflowY === "auto" ||
            style.overflowY === "scroll"
          ) {
            animateScrollIntoView(ref.current, parent, {
              block: "end",
              duration: 0.8,
              ease: TgbResolverEasings.inOutQuad,
            });
            return;
          }
          parent = parent.parentElement;
        }
      });
    });

    return (
      <MotionRow
        ref={ref}
        position="relative"
        layout="position"
        layoutScroll
        variants={variants}
        animate={currentVariant}
        transition={{
          layout: {
            duration: 0.8,
            ease: TgbResolverEasings.swiftOut,
          },
          backgroundColor: {
            duration: 0.15,
            ease: TgbResolverEasings.inOutQuad,
          },
        }}
        zIndex={isCurrentResolved ? 5 : 0}
      >
        <RankCell rank={data.rank} isCurrentResolved={isCurrentResolved} />

        <UsernameCell realName={data.realName} username={data.username} />

        {data.problems.map((problem) => (
          <ProblemCell key={problem.problemId} problem={problem} />
        ))}

        <ScoreCell score={data.totalScore} />
        <PenaltyCell penalty={data.totalPenalty} />

        <SubmissionTimeCell
          submissionTimeSinceStartSeconds={Math.max(
            ...data.problems.map((p) => p.timeSinceStart),
            data.lastSubmittedSeconds ?? 0,
            0,
          )}
        />
      </MotionRow>
    );
  },
  (prev, next) =>
    entryEqual(prev.data, next.data) && prev.isCurrentResolved === next.isCurrentResolved,
);

// apps/web-vue/src/features/leaderboard/leaderboard-row.vue
<script setup lang="ts">
import { css, cx } from "@styled-system/css";
import { Box, VStack } from "@styled-system/jsx";
import { table } from "@styled-system/recipes";
import type { LeaderboardEntry } from "@tgb-resolver/realtime";
import { computed, inject, onMounted, type Ref, ref, watch } from "vue";

import { TgbResolverEasings } from "@/features/shared/anim/easings";

import { formatTime } from "./cells";
import { useLeaderboardStore } from "./leaderboard-store";
import ProblemCell from "./problem-cell.vue";
import { animateScrollIntoView } from "./utils/scroll";

const props = defineProps<{
  data: LeaderboardEntry;
  isCurrentResolved: boolean;
}>();

const rowRef = ref<HTMLTableRowElement | null>(null);
const leaderboardStore = useLeaderboardStore();
const isBigScreen = inject<Ref<boolean>>(
  "isBigScreen",
  computed(() => false),
);
const classes = computed(() =>
  table({ size: isBigScreen.value ? "lg" : "md", variant: "line", stickyHeader: true }),
);

const submissionTimeSinceStartSeconds = computed(() =>
  Math.max(
    ...props.data.problems.map((p) => p.timeSinceStart),
    props.data.lastSubmittedSeconds ?? 0,
    0,
  ),
);

const formattedTime = computed(() => formatTime(submissionTimeSinceStartSeconds.value));

function checkAndScroll() {
  const targetId = leaderboardStore.currentBottomView;
  if (targetId !== props.data.userId || !rowRef.value) return;

  requestAnimationFrame(() => {
    if (!rowRef.value) return;
    let parent: HTMLElement | null = rowRef.value.parentElement;
    while (parent) {
      const style = getComputedStyle(parent);
      if (
        style.overflow === "auto" ||
        style.overflow === "scroll" ||
        style.overflowY === "auto" ||
        style.overflowY === "scroll"
      ) {
        animateScrollIntoView(rowRef.value, parent, {
          block: "end",
          duration: 0.8,
          ease: TgbResolverEasings.inOutQuad,
        });
        return;
      }
      parent = parent.parentElement;
    }
  });
}

watch(() => leaderboardStore.currentBottomView, checkAndScroll);
onMounted(checkAndScroll);
</script>

<template>
  <tr
    ref="rowRef"
    :class="
      cx(
        classes.row,
        css({
          position: 'relative',
          zIndex: isCurrentResolved ? 5 : 0,
          backgroundColor: isCurrentResolved ? 'yellow.700' : undefined,
          transition: 'background-color 0.15s cubic-bezier(0.45, 0, 0.55, 1)',
        }),
      )
    "
    :data-current="isCurrentResolved || undefined"
  >
    <td
      :class="
        cx(
          classes.cell,
          css({
            textAlign: 'end',
            fontFamily: 'mono',
          }),
        )
      "
    >
      {{ data.rank }}
    </td>

    <td :class="classes.cell" style="max-width: 30ch">
      <VStack alignItems="start" gap="1">
        <Box fontWeight="medium">{{ data.realName }}</Box>
        <Box fontFamily="mono" fontStyle="italic" fontSize="xs" color="fg.muted">
          {{ data.username }}
        </Box>
      </VStack>
    </td>

    <ProblemCell v-for="problem in data.problems" :key="problem.problemId" :problem="problem" />

    <td
      :class="
        cx(
          classes.cell,
          css({
            textAlign: 'end',
            fontFamily: 'mono',
          }),
        )
      "
    >
      {{ data.totalScore }}
    </td>

    <td
      :class="
        cx(
          classes.cell,
          css({
            textAlign: 'end',
            fontFamily: 'mono',
          }),
        )
      "
    >
      {{ data.totalPenalty }}
    </td>

    <td
      :class="
        cx(
          classes.cell,
          css({
            textAlign: 'end',
            fontFamily: 'mono',
            fontStyle: 'italic',
          }),
        )
      "
    >
      {{ formattedTime }}
    </td>
  </tr>
</template>
