// apps/web/src/features/control/control-confirm-dialog.vue
<script setup lang="ts">
import { Dialog } from "@ark-ui/vue";
import { css, cx } from "@styled-system/css";
import { button, dialog, field, input } from "@styled-system/recipes";
import { nextTick, useTemplateRef, watch } from "vue";

import { useConfirmActionStore } from "@/stores/confirm-action-store";

const store = useConfirmActionStore();
const dialogClasses = dialog({ placement: "center", size: "sm" });
const fieldClasses = field();
const inputClasses = input({ size: "md" });

const content = css({ display: "flex", flexDirection: "column", gap: "4", alignItems: "stretch", padding: "6" });
const message = css({ color: "fg.muted", fontSize: "sm" });
const actions = css({ display: "flex", justifyContent: "flex-end", gap: "3" });

const inputRef = useTemplateRef<HTMLInputElement>("inputRef");

watch(
  () => [store.open, store.showInput],
  ([isOpen, isShowInput]) => {
    if (isOpen && isShowInput) {
      nextTick(() => {
        inputRef.value?.focus();
        inputRef.value?.select();
      });
    }
  },
);
</script>

<template>
  <Dialog.Root
    :open="store.open"
    role="alertdialog"
    @escape-key-down="store.resolveConfirmAction(false)"
    @pointer-down-outside="store.resolveConfirmAction(false)"
  >
    <Dialog.Backdrop :class="dialogClasses.backdrop" />
    <Dialog.Positioner :class="dialogClasses.positioner">
      <Dialog.Content :class="dialogClasses.content">
        <div :class="content">
          <Dialog.Title :class="dialogClasses.title">{{ store.title }}</Dialog.Title>

          <div v-if="store.showInput" :class="fieldClasses.root">
            <label for="control-dialog-input" :class="fieldClasses.label">{{ store.inputLabel || store.message }}</label>
            <input
              id="control-dialog-input"
              ref="inputRef"
              :class="inputClasses"
              :value="store.inputValue"
              @input="(e: Event) => store.setInputValue((e.target as HTMLInputElement).value)"
              @keydown.enter="store.resolveConfirmAction(true)"
            />
          </div>
          <p v-else :class="message">{{ store.message }}</p>

          <div :class="actions">
            <button
              type="button"
              :class="button({ variant: 'outline' })"
              @click="store.resolveConfirmAction(false)"
            >
              {{ store.cancelLabel }}
            </button>
            <button
              type="button"
              :class="
                cx(
                  button(),
                  css({ colorPalette: store.showInput ? 'blue' : 'red' }),
                )
              "
              @click="store.resolveConfirmAction(true)"
            >
              {{ store.confirmLabel }}
            </button>
          </div>
        </div>
      </Dialog.Content>
    </Dialog.Positioner>
  </Dialog.Root>
</template>

// apps/web/src/features/control/control-confirm-dialog.tsx
import { Button, Dialog, Field, Input, Portal } from "@chakra-ui/react";

import { confirmActionModel } from "@/features/shared/confirm-action-model";

export function ControlConfirmDialog() {
  const open = confirmActionModel.open.value;
  const showInput = confirmActionModel.showInput.value;
  const title = confirmActionModel.title;
  const message = confirmActionModel.message;
  const confirmLabel = confirmActionModel.confirmLabel;
  const cancelLabel = confirmActionModel.cancelLabel;

  return (
    <Dialog.Root
      size="sm"
      open={open}
      role="alertdialog"
      onEscapeKeyDown={() => confirmActionModel.resolveConfirmAction(false)}
      onInteractOutside={() => confirmActionModel.resolveConfirmAction(false)}
    >
      <Portal>
        <Dialog.Backdrop />
        <Dialog.Positioner>
          <Dialog.Content>
            <Dialog.Header>
              <Dialog.Title>
                <>{title}</>
              </Dialog.Title>
            </Dialog.Header>
            <Dialog.Body>
              {showInput ? (
                <Field.Root>
                  <Field.Label>
                    <>{message}</>
                  </Field.Label>
                  <Input
                    defaultValue={confirmActionModel.inputValue.value}
                    onChange={(e) => confirmActionModel.setInputValue(e.target.value)}
                    onKeyDown={(e) => {
                      if (e.key === "Enter") {
                        confirmActionModel.resolveConfirmAction(true);
                      }
                    }}
                    autoFocus
                  />
                </Field.Root>
              ) : (
                <>{message}</>
              )}
            </Dialog.Body>
            <Dialog.Footer gap="3">
              <Dialog.ActionTrigger asChild>
                <Button
                  variant="outline"
                  onClick={() => confirmActionModel.resolveConfirmAction(false)}
                >
                  <>{cancelLabel}</>
                </Button>
              </Dialog.ActionTrigger>
              <Button
                colorPalette={showInput ? "colorPalette" : "red"}
                onClick={() => confirmActionModel.resolveConfirmAction(true)}
              >
                <>{confirmLabel}</>
              </Button>
            </Dialog.Footer>
          </Dialog.Content>
        </Dialog.Positioner>
      </Portal>
    </Dialog.Root>
  );
}
