// apps/web/src/features/control/floating-panel-host.vue
<script setup lang="ts">
import { useEventListener } from "@vueuse/core";
import { type Component, computed } from "vue";

import CreateEventPanel from "@/features/control/create-event-panel.vue";
import FloatingPanelFrame from "@/features/control/floating-panel-frame.vue";
import { useFloatingPanelStore } from "@/features/control/floating-panel-store";
import {
  type FloatingPanelHandle,
  FloatingPanelType,
  floatingPanelConfig,
} from "@/features/control/floating-panel-types";
import ImportShowPanel from "@/features/control/import-show-panel.vue";
import InspectShowPanel from "@/features/control/inspect-show-panel.vue";
import ExtensionConfigPanel from "@/features/extensions/config-panel.vue";

const store = useFloatingPanelStore();

const PANEL_REGISTRY: Record<FloatingPanelType, Component> = {
  [FloatingPanelType.ExtensionConfig]: ExtensionConfigPanel,
  [FloatingPanelType.CreateEvent]: CreateEventPanel,
  [FloatingPanelType.ImportShow]: ImportShowPanel,
  [FloatingPanelType.InspectShow]: InspectShowPanel,
};

const panelsView = computed(() =>
  store.panels.map((panel) => ({
    panel,
    config: floatingPanelConfig[panel.type],
    title: panel.title.value,
    body: PANEL_REGISTRY[panel.type],
  })),
);

function getDefaultPosition(size: { width: number; height: number }) {
  return {
    x: Math.max(0, (window.innerWidth - size.width) / 2),
    y: Math.max(0, (window.innerHeight - size.height) / 2),
  };
}

function onOpenChange(panel: FloatingPanelHandle, open: boolean) {
  if (!open) void store.requestFloatingPanelClose(panel);
}

useEventListener(window, "beforeunload", (event) => {
  if (store.hasDirtyPanels) {
    event.preventDefault();
  }
});
</script>

<template>
  <Teleport to="body">
    <FloatingPanelFrame
      v-for="entry in panelsView"
      :key="entry.panel.id"
      :open="true"
      :title="entry.title"
      :icon="entry.config.icon"
      :maximizable="entry.config.maximizable ?? false"
      :default-size="entry.config.size"
      :min-size="entry.config.minSize"
      :default-position="getDefaultPosition(entry.config.size)"
      :resizable="entry.config.resizable ?? true"
      :allow-overflow="false"
      :close-on-escape="true"
      strategy="fixed"
      @open-change="(details: { open: boolean }) => onOpenChange(entry.panel, details.open)"
      @close="store.requestFloatingPanelClose(entry.panel)"
    >
      <component :is="entry.body" :panel="entry.panel" />
    </FloatingPanelFrame>
  </Teleport>
</template>

// apps/web/src/features/control/floating-panel-host.tsx
import { FloatingPanel, IconButton, Portal } from "@chakra-ui/react";
import { GripHorizontal, Maximize2, Minimize2, X } from "lucide-react";
import { useEffect } from "react";

import { floatingPanelModel } from "@/features/control/floating-panel-model";
import { getDefaultFloatingPanelPosition } from "@/features/control/floating-panel-position";
import {
  floatingPanelComponents,
  floatingPanelConfig,
} from "@/features/control/floating-panel-types";

export function FloatingPanelHost() {
  const panels = floatingPanelModel.panels.value;

  useEffect(() => {
    const onBeforeUnload = (event: BeforeUnloadEvent) => {
      if (floatingPanelModel.hasDirtyPanels.value) {
        event.preventDefault();
      }
    };
    window.addEventListener("beforeunload", onBeforeUnload);
    return () => window.removeEventListener("beforeunload", onBeforeUnload);
  }, []);

  return (
    <>
      {panels.map((panel) => {
        const PanelComponent = floatingPanelComponents[panel.type];
        const config = floatingPanelConfig[panel.type];
        const resizable = config?.resizable ?? true;
        const defaultSize = config?.size ?? { width: 640, height: 480 };

        return (
          <FloatingPanel.Root
            key={panel.id}
            allowOverflow={false}
            closeOnEscape
            open
            resizable={resizable}
            defaultSize={defaultSize}
            defaultPosition={getDefaultFloatingPanelPosition(defaultSize, {
              width: window.innerWidth,
              height: window.innerHeight,
            })}
            minSize={config?.minSize}
            onOpenChange={(details) => {
              if (!details.open) {
                void floatingPanelModel.requestFloatingPanelClose(panel);
              }
            }}
          >
            <Portal>
              <FloatingPanel.Positioner>
                <FloatingPanel.Content>
                  <FloatingPanel.Header>
                    <FloatingPanel.DragTrigger>
                      <GripHorizontal size={16} />
                      <FloatingPanel.Title>{panel.title}</FloatingPanel.Title>
                    </FloatingPanel.DragTrigger>
                    <FloatingPanel.Control>
                      {config?.maximizable && (
                        <>
                          <FloatingPanel.StageTrigger stage="maximized" asChild>
                            <IconButton aria-label="Maximize panel" size="2xs" variant="ghost">
                              <Maximize2 size={14} />
                            </IconButton>
                          </FloatingPanel.StageTrigger>
                          <FloatingPanel.StageTrigger stage="default" asChild>
                            <IconButton aria-label="Restore panel" size="2xs" variant="ghost">
                              <Minimize2 size={14} />
                            </IconButton>
                          </FloatingPanel.StageTrigger>
                        </>
                      )}
                      <IconButton
                        aria-label="Close panel"
                        size="2xs"
                        variant="ghost"
                        onClick={() => void floatingPanelModel.requestFloatingPanelClose(panel)}
                      >
                        <X size={14} />
                      </IconButton>
                    </FloatingPanel.Control>
                  </FloatingPanel.Header>
                  <FloatingPanel.Body p={4}>
                    {PanelComponent ? (
                      <PanelComponent panel={panel} {...panel.props.value} />
                    ) : null}
                  </FloatingPanel.Body>
                  {resizable && <FloatingPanel.ResizeTriggers />}
                </FloatingPanel.Content>
              </FloatingPanel.Positioner>
            </Portal>
          </FloatingPanel.Root>
        );
      })}
    </>
  );
}
