// apps/web-vue/src/features/control/realtime-provider.vue
<script setup lang="ts">
import { useQueryClient } from "@tanstack/vue-query";
import type { ShowWebSocketMessage } from "@tgb-resolver/realtime";
import { ShowConnectionStatus } from "@tgb-resolver/realtime";
import { onUnmounted, ref, watch } from "vue";

import BigRefetchOverlay from "@/features/control/big-refetch-overlay.vue";
import { useControlShowQuery } from "@/features/control/composables/use-show";
import { usePlaybackStore } from "@/features/control/playback-store";
import { connectRealtime } from "@/lib/realtime-client";
import { useRealtimeStore } from "@/stores/realtime-store";
import { useShowStore } from "@/stores/show-store";

import { applyControlRealtimeMessage, controlShowQueryKey } from "./realtime-handler";
import { mapShowStateSnapshotToShowFile } from "./show-mapper";

const queryClient = useQueryClient();
const realtimeStore = useRealtimeStore();
const showStore = useShowStore();
const playbackStore = usePlaybackStore();

const showQuery = useControlShowQuery();

let disconnect: (() => void) | null = null;
disconnect = connectRealtime(
  (status) => {
    realtimeStore.connectionStatus = status;

    if (status === ShowConnectionStatus.Connected) {
      void queryClient.invalidateQueries({ queryKey: controlShowQueryKey() });
    }
  },
  (message: ShowWebSocketMessage) => {
    void applyControlRealtimeMessage(queryClient, message);
  },
);

onUnmounted(() => {
  disconnect?.();
});

const syncPlaybackRef = ref(false);

watch(
  () => showQuery.data.value,
  (data) => {
    if (!data?.playback) {
      return;
    }

    showStore.hydrateFromSnapshot(data);

    playbackStore.syncVersion(data.showVersion ?? 0);

    if (!syncPlaybackRef.value) {
      syncPlaybackRef.value = true;
      playbackStore.syncFromSnapshot(data.showVersion ?? 0, data.playback);
    }

    realtimeStore.bigRefetching = false;
  },
);
</script>

<template>
  <slot />
  <BigRefetchOverlay />
</template>

// apps/web/src/features/control/realtime-provider.tsx
import { useQuery, useQueryClient } from "@tanstack/react-query";
import {
  generatedClient,
  tgbResolverServerFeaturesShowGetShowEndpointOptions,
} from "@tgb-resolver/contracts";
import { ShowConnectionStatus, type ShowWebSocketMessage } from "@tgb-resolver/realtime";
import { type ReactNode, useEffect } from "react";

import { BigRefetchOverlay } from "@/components/control/big-refetch-overlay";
import { connectRealtime } from "@/lib/realtime-client";
import { playbackModel, realtimeModel, showModel } from "@/models";

import { applyControlRealtimeMessage, controlShowQueryKey } from "./realtime-handler";
import { mapShowStateSnapshotToShowFile } from "./show-mapper";

export function ControlRealtimeProvider({ children }: { children: ReactNode }) {
  const queryClient = useQueryClient();

  const showQuery = useQuery({
    ...tgbResolverServerFeaturesShowGetShowEndpointOptions({ client: generatedClient }),
    queryKey: controlShowQueryKey(),
    select: mapShowStateSnapshotToShowFile,
  });

  useEffect(() => {
    const disconnect = connectRealtime(
      (status) => {
        realtimeModel.connectionStatus.value = status;

        if (status === ShowConnectionStatus.Connected) {
          void queryClient.invalidateQueries({ queryKey: controlShowQueryKey() });
        }
      },
      (message: ShowWebSocketMessage) => {
        void applyControlRealtimeMessage(queryClient, message);
      },
    );
    return disconnect;
  }, [queryClient]);

  useEffect(() => {
    if (!showQuery.data?.playback) {
      return;
    }

    showModel.hydrateFromSnapshot(showQuery.data);
    playbackModel.syncFromSnapshot(showQuery.data.showVersion ?? 0, showQuery.data.playback);
    realtimeModel.bigRefetching.value = false;
  }, [showQuery.data]);

  return (
    <>
      {children}
      <BigRefetchOverlay />
    </>
  );
}
