// apps/web/src/features/leaderboard/leaderboard-row.vue
<script setup lang="ts">
import { cva } from "@styled-system/css";
import type { LeaderboardEntry } from "@tgb-resolver/realtime";
import { computed } from "vue";

import { useLeaderboardStore } from "@/stores/leaderboard-store";

import PenaltyCell from "./cells/penalty-cell.vue";
import RankCell from "./cells/rank-cell.vue";
import ScoreCell from "./cells/score-cell.vue";
import SubmissionTimeCell from "./cells/submission-time-cell.vue";
import UsernameCell from "./cells/username-cell.vue";
import ProblemCell from "./problem-cell.vue";

const props = defineProps<{ data: LeaderboardEntry; isCurrentResolved: boolean; flip?: boolean }>();

const leaderboardStore = useLeaderboardStore();

const submissionTimeSinceStartSeconds = computed(() =>
  Math.max(
    ...props.data.problems.map((p) => p.timeSinceStart),
    props.data.lastSubmittedSeconds ?? 0,
  ),
);

// Only the problem cell of the most recent PRE/RES event blinks.
function isLatestResolved(problemId: number): boolean {
  const latest = leaderboardStore.latestResolved;
  return (
    latest !== null && latest.userId === props.data.userId && latest.problemId === problemId
  );
}

// Background stays CSS-owned (token + _dark condition) so it always matches
// the active color mode. Rows are virtualized with fixed heights (44px
// standard, 76px big-screen) matching the parent virtualizer estimate, so
// translate offsets stay exact. The transform transition powers
// TransitionGroup FLIP on rank swaps and is only enabled via `flip` in the
// unvirtualized path: in virtual mode the inline virtual translate changes
// every scroll frame, and a transform transition would make rows trail.
const rowClass = cva({
  base: {
    position: "relative",
    zIndex: 0,
    height: "11",
    backgroundColor: "bg",
    transitionProperty: "background-color",
    transitionDuration: "0.15s",
    transitionTimingFunction: "inOutQuad",
  },
  variants: {
    current: {
      true: {
        zIndex: 5,
        backgroundColor: "yellow.300",
        _dark: { backgroundColor: "yellow.700" },
      },
    },
    big: { true: { height: "19" } },
    flip: {
      true: {
        transitionProperty: "transform, background-color",
        transitionDuration: "0.8s, 0.15s",
      },
    },
  },
});
</script>

<template>
  <tr
    :data-user-id="data.userId"
    :class="rowClass({ current: isCurrentResolved, big: leaderboardStore.isBigScreen, flip: flip })"
  >
    <RankCell :rank="data.rank" />

    <UsernameCell :real-name="data.realName" :username="data.username" />

    <ProblemCell
      v-for="problem in data.problems"
      :key="problem.problemId"
      :problem="problem"
      :is-latest-resolved="isLatestResolved(problem.problemId)"
    />

    <ScoreCell :score="data.totalScore" />
    <PenaltyCell :penalty="data.totalPenalty" />

    <SubmissionTimeCell :submission-time-since-start-seconds="submissionTimeSinceStartSeconds" />
  </tr>
</template>

// apps/web/src/features/leaderboard/leaderboard-row.tsx
import { useToken } from "@chakra-ui/react";
import { useSignalEffect } from "@preact/signals-react";
import type { LeaderboardEntry } from "@tgb-resolver/realtime";
import { motion, type Variants } from "motion/react";
import { memo, useMemo, useRef } from "react";

import { leaderboardModel } from "@/features/leaderboard/leaderboard-model";
import { animateScrollIntoView } from "@/features/leaderboard/utils/scroll";
import { useColorMode } from "@/features/shared/ui/color-mode";
import { entryEqual } from "@/lib/leaderboard-comparators";

import { TgbResolverEasings } from "../shared/anim/easings";
import { PenaltyCell, RankCell, ScoreCell, SubmissionTimeCell, UsernameCell } from "./cells";
import { ProblemCell } from "./problem-cell";

// TODO: adjust animation timings to be relative to whole event's duration
// TODO: submission count to show a contestant's effort on a problem, and we'll show the verdict on those individual attempt also
// TODO: rank number anim
// TODO: update with a pending, pending-active state, as currently it it's turning "unexpectedly" from Unknown to Pending
// on PRE-RES, which is kinda bad on the UX side of things

const MotionRow = motion.create("tr");

interface LeaderboardRowProps {
  data: LeaderboardEntry;
  isCurrentResolved: boolean;
}

export const LeaderboardRow = memo(
  ({ data, isCurrentResolved }: LeaderboardRowProps) => {
    const [normalBg, darkBg, lightBg] = useToken("colors", ["bg", "yellow.700", "yellow.300"]);
    const { colorMode } = useColorMode();

    const variants: Variants = useMemo(
      () => ({
        dark: { backgroundColor: normalBg },
        darkCurrent: { backgroundColor: darkBg },
        light: { backgroundColor: normalBg },
        lightCurrent: { backgroundColor: lightBg },
      }),
      [normalBg, darkBg, lightBg],
    );

    const currentVariant = useMemo(() => {
      if (colorMode === "dark") {
        return isCurrentResolved ? "darkCurrent" : "dark";
      } else {
        return isCurrentResolved ? "lightCurrent" : "light";
      }
    }, [colorMode, isCurrentResolved]);

    const ref = useRef<HTMLTableRowElement>(null);
    const submissionTimeSinceStartSeconds = Math.max(
      ...data.problems.map((p) => p.timeSinceStart),
      data.lastSubmittedSeconds ?? 0,
      0,
    );

    useSignalEffect(() => {
      const targetId = leaderboardModel.currentBottomView.value;
      if (targetId !== data.userId) return;

      requestAnimationFrame(() => {
        if (!ref.current) return;

        let parent: HTMLElement | null = ref.current.parentElement;
        while (parent) {
          const style = getComputedStyle(parent);
          if (
            style.overflow === "auto" ||
            style.overflow === "scroll" ||
            style.overflowY === "auto" ||
            style.overflowY === "scroll"
          ) {
            animateScrollIntoView(ref.current, parent, {
              block: "end",
              duration: 0.8,
              ease: TgbResolverEasings.inOutQuad,
            });
            return;
          }
          parent = parent.parentElement;
        }
      });
    });

    return (
      <MotionRow
        ref={ref}
        style={{
          position: "relative",
          zIndex: isCurrentResolved ? 5 : 0,
        }}
        layout="position"
        layoutScroll
        variants={variants}
        animate={currentVariant}
        transition={{
          layout: {
            duration: 0.8,
            ease: TgbResolverEasings.swiftOut,
          },
          backgroundColor: {
            duration: 0.15,
            ease: TgbResolverEasings.inOutQuad,
          },
        }}
      >
        <RankCell rank={data.rank} isCurrentResolved={isCurrentResolved} />

        <UsernameCell realName={data.realName} username={data.username} />

        {data.problems.map((problem) => (
          <ProblemCell key={problem.problemId} problem={problem} />
        ))}

        <ScoreCell score={data.totalScore} />
        <PenaltyCell penalty={data.totalPenalty} />

        <SubmissionTimeCell submissionTimeSinceStartSeconds={submissionTimeSinceStartSeconds} />
      </MotionRow>
    );
  },
  (prev, next) =>
    entryEqual(prev.data, next.data) && prev.isCurrentResolved === next.isCurrentResolved,
);
