// apps/web/src/features/leaderboard/leaderboard-table.vue
<script setup lang="ts">
import { css, cx } from "@styled-system/css";
import { table } from "@styled-system/recipes";
import type { ProblemDefinition } from "@tgb-resolver/realtime";
import { storeToRefs } from "pinia";
import { computed, TransitionGroup } from "vue";

import { useLeaderboardStore } from "@/stores/leaderboard-store";

defineProps<{ problems?: ProblemDefinition[] }>();

const { isBigScreen } = storeToRefs(useLeaderboardStore());

const classes = computed(() =>
  table({ size: isBigScreen.value ? "lg" : "sm", variant: "line", stickyHeader: true }),
);
</script>

<template>
  <table
    :class="
      cx(
        classes.root,
        css({
          borderCollapse: 'collapse',
          borderSpacing: 0,
          fontSize: isBigScreen ? '2xl' : undefined,
          lineHeight: isBigScreen ? 'tall' : undefined,
        }),
      )
    "
  >
    <thead :class="cx(classes.header, css({ position: 'relative', zIndex: 999 }))">
      <tr :class="classes.row">
        <th :class="cx(classes.columnHeader, css({ textAlign: 'end', borderBottomWidth: 2, borderBottomColor: 'border' }))">
          Rank
        </th>
        <th :class="cx(classes.columnHeader, css({ borderBottomWidth: 2, borderBottomColor: 'border' }))">
          User
        </th>

        <th
          v-for="problem in problems"
          :key="problem.id"
          :class="cx(classes.columnHeader, css({ borderBottomWidth: 2, borderBottomColor: 'border' }))"
          :style="{ width: isBigScreen ? '14rem' : '8ch', height: '2rem' }"
        >
          <div
            v-if="isBigScreen"
            :class="css({ display: 'grid', gridTemplateRows: '1fr 2fr', height: 'full', gap: 2 })"
          >
            <div :class="css({ display: 'flex', alignItems: 'center', justifyContent: 'center' })">
              <span :class="css({ fontFamily: 'mono' })">{{ problem.label }}</span>
            </div>
            <div :class="css({ textAlign: 'center', overflow: 'hidden', lineClamp: 2 })">
              {{ problem.name }}
            </div>
          </div>
          <div v-else :class="css({ display: 'flex', alignItems: 'center', justifyContent: 'center' })">
            <span :class="css({ fontFamily: 'mono' })">{{ problem.label }}</span>
          </div>
        </th>

        <th :class="cx(classes.columnHeader, css({ textAlign: 'end', borderBottomWidth: 2, borderBottomColor: 'border' }))">
          Score
        </th>
        <th :class="cx(classes.columnHeader, css({ textAlign: 'end', borderBottomWidth: 2, borderBottomColor: 'border' }))">
          Penalty
        </th>
        <th :class="cx(classes.columnHeader, css({ textAlign: 'end', borderBottomWidth: 2, borderBottomColor: 'border' }))">
          Time
        </th>
      </tr>
    </thead>
    <!-- TransitionGroup FLIP-animates rows when rank swaps reorder them. -->
    <TransitionGroup tag="tbody" name="leaderboard-row" :class="classes.body">
      <slot />
    </TransitionGroup>
  </table>
</template>

// apps/web/src/features/leaderboard/leaderboard-table.tsx
import { Center, Grid, Table, Text } from "@chakra-ui/react";
import type { ProblemDefinition } from "@tgb-resolver/realtime";
import type { CSSProperties, ReactNode } from "react";

import { useIsBigScreen } from "./leaderboard-provider";

const END_ALIGN_STYLE: CSSProperties = { textAlign: "end" };

interface LeaderboardTableProps {
  problems: ProblemDefinition[] | undefined;
  children: ReactNode;
}

export function LeaderboardTable({ problems, children }: LeaderboardTableProps) {
  const isBigScreen = useIsBigScreen().value;

  return (
    <Table.Root
      size={isBigScreen ? "lg" : "sm"}
      native
      stickyHeader
      css={{
        "& *": isBigScreen && {
          fontSize: "2xl",
          lineHeight: "tall",
        },
        borderCollapse: "separate",
        borderSpacing: 0,
        "& thead": {
          position: "relative",
          zIndex: 999,
        },
        "& thead th": {
          borderBottomWidth: 2,
          borderBottomColor: "border",
        },
      }}
    >
      <thead>
        <tr>
          <th style={END_ALIGN_STYLE}>Rank</th>
          <th>User</th>

          {problems?.map((problem) => (
            <th key={problem.id} style={{ width: isBigScreen ? "14rem" : "8ch", height: "2rem" }}>
              {isBigScreen ? (
                <Grid templateRows="1fr 2fr" h="full" gap={2}>
                  <Center>
                    <Text fontFamily="mono">{problem.label}</Text>
                  </Center>
                  <Text textAlign="center" maxW="full" lineClamp={2}>
                    {problem.name}
                  </Text>
                </Grid>
              ) : (
                <Center>
                  <Text fontFamily="mono">{problem.label}</Text>
                </Center>
              )}
            </th>
          ))}

          <th style={END_ALIGN_STYLE}>Score</th>
          <th style={END_ALIGN_STYLE}>Penalty</th>
          <th style={END_ALIGN_STYLE}>Time</th>
        </tr>
      </thead>

      <tbody>{children}</tbody>
    </Table.Root>
  );
}
