// apps/web/src/components/control/big-refetch-overlay.tsx
import { Box, Spinner, Text, VStack } from "@chakra-ui/react";

import { bigRefetching } from "@/features/control/realtime-cache";

export function BigRefetchOverlay() {
  if (!bigRefetching.value) {
    return null;
  }

  return (
    <Box
      alignItems="center"
      background="blackAlpha.700"
      display="flex"
      inset="0"
      justifyContent="center"
      position="fixed"
      zIndex="toast"
    >
      <VStack gap="4">
        <Spinner size="xl" />
        <Text color="fg.muted" fontSize="sm">
          Syncing show…
        </Text>
      </VStack>
    </Box>
  );
}

// apps/web-vue/src/features/control/big-refetch-overlay.vue
<script setup lang="ts">
import { Box, VStack } from "@styled-system/jsx";

import UiSpinner from "@/features/shared/ui/spinner.vue";
import { useRealtimeStore } from "@/stores/realtime-store";

const realtimeStore = useRealtimeStore();
</script>

<template>
  <Box
    v-if="realtimeStore.bigRefetching"
    alignItems="center"
    display="flex"
    inset="0"
    justifyContent="center"
    position="fixed"
    zIndex="toast"
    bg="blackAlpha.700"
  >
    <VStack gap="4">
      <UiSpinner size="xl" label="" aria-hidden="true" />
      <Box as="p" color="fg.muted" fontSize="sm">Syncing show…</Box>
    </VStack>
  </Box>
</template>
