// apps/web/src/features/control/inspect-show-panel.tsx
import { Box, Code, Text } from "@chakra-ui/react";

import type { FloatingPanelHandle } from "@/features/control/floating-panel-model";
import { showModel } from "@/features/shared/show-model";

export function InspectShowPanel({ panel: _panel }: { panel: FloatingPanelHandle }) {
  const file = showModel.showFile.value;

  if (!file) {
    return <Text color="fg.muted">No show loaded.</Text>;
  }

  return (
    <Box h="full" overflow="auto">
      <Code display="block" whiteSpace="pre-wrap" p={2}>
        {JSON.stringify(file, null, 2)}
      </Code>
    </Box>
  );
}

// apps/web-vue/src/features/control/inspect-show-panel.vue
<script setup lang="ts">
import { css } from "@styled-system/css";
import { computed } from "vue";

import type { FloatingPanelHandle } from "@/features/control/floating-panel-types";
import { useShowStore } from "@/stores/show-store";

defineProps<{
  panel?: FloatingPanelHandle;
}>();

const showStore = useShowStore();
const file = computed(() => showStore.showFile);

const root = css({ height: "full", overflow: "auto" });
const empty = css({ color: "fg.muted" });
const code = css({
  display: "block",
  fontFamily: "mono",
  fontSize: "xs",
  whiteSpace: "pre-wrap",
  padding: "2",
  bg: "bg.muted",
  rounded: "md",
});
</script>

<template>
  <div :class="root">
    <p v-if="!file" :class="empty">
      No show loaded.
    </p>
    <pre v-else :class="code">{{ JSON.stringify(file, null, 2) }}</pre>
  </div>
</template>
