// apps/web/src/components/control/panels/control-timeline-panel.tsx
import { Grid } from "@chakra-ui/react";
import { ControlTimelineTable } from "../timeline/timeline-table";
import { ControlTimelineControls } from "./timeline/control-timeline-controls";

export function ControlTimelinePanel() {
  return (
    <Grid templateRows="1fr auto" h="full">
      <ControlTimelineTable />

      <ControlTimelineControls />
    </Grid>
  );
}

// apps/web-vue/src/features/control/panels/control-timeline-panel.vue
<script setup lang="ts">
import { Grid } from "@styled-system/jsx";

import ControlTimelineControls from "@/features/control/panels/timeline/control-timeline-controls.vue";
import ControlTimelineTable from "@/features/control/timeline/timeline-table.vue";
</script>

<template>
  <Grid templateRows="1fr auto" h="full">
    <ControlTimelineTable />
    <ControlTimelineControls />
  </Grid>
</template>
