// apps/web/src/components/control/panels/control-main-panel.tsx
import { Grid } from "@chakra-ui/react";

import { useControlIsLive } from "@/features/control/hooks";

import { ControlEditMainPanel } from "./main/control-edit-main-panel";
import { ControlLiveMainPanel } from "./main/control-live-main-panel";
import { ControlMainControls } from "./main/control-main-controls";

export function ControlMainPanel() {
  const isLive = useControlIsLive();
  return (
    <Grid templateRows="1fr auto" h="full">
      {isLive ? <ControlLiveMainPanel /> : <ControlEditMainPanel />}

      <ControlMainControls />
    </Grid>
  );
}

// apps/web-vue/src/features/control/panels/control-main-panel.vue
<script setup lang="ts">
import { Grid } from "@styled-system/jsx";

import { useControlIsLive } from "@/features/control/composables/use-show";
import ControlEditMainPanel from "@/features/control/panels/main/control-edit-main-panel.vue";
import ControlLiveMainPanel from "@/features/control/panels/main/control-live-main-panel.vue";
import ControlMainControls from "@/features/control/panels/main/control-main-controls.vue";

const isLive = useControlIsLive();
</script>

<template>
  <Grid templateRows="1fr auto" h="full">
    <ControlLiveMainPanel v-if="isLive" />
    <ControlEditMainPanel v-else />
    <ControlMainControls />
  </Grid>
</template>
