// apps/web-vue/src/features/control/control-confirm-dialog.vue
<script setup lang="ts">
import {
  DialogBackdrop,
  DialogContent,
  DialogPositioner,
  DialogRoot,
  DialogTitle,
} from "@ark-ui/vue";
import { Box, VStack } from "@styled-system/jsx";
import { dialog } from "@styled-system/recipes";

import UiButton from "@/features/shared/ui/button.vue";
import { useConfirmActionStore } from "@/stores/confirm-action-store";

defineOptions({ name: "ControlConfirmDialog" });

const store = useConfirmActionStore();
const dialogClasses = dialog({ placement: "center", size: "sm" });
</script>

<template>
  <DialogRoot
    :open="store.open"
    role="alertdialog"
    @escape-key-down="store.resolveConfirmAction(false)"
  >
    <DialogBackdrop :class="dialogClasses.backdrop" />
    <DialogPositioner :class="dialogClasses.positioner">
      <DialogContent :class="dialogClasses.content">
        <VStack alignItems="stretch" gap="4" p="6">
          <DialogTitle :class="dialogClasses.title">{{ store.title }}</DialogTitle>
          <Box color="fg.muted" fontSize="sm">{{ store.message }}</Box>
          <Box display="flex" justifyContent="flex-end" gap="3">
            <UiButton variant="outline" @click="store.resolveConfirmAction(false)">
              {{ store.cancelLabel }}
            </UiButton>
            <UiButton colorPalette="red" @click="store.resolveConfirmAction(true)">
              {{ store.confirmLabel }}
            </UiButton>
          </Box>
        </VStack>
      </DialogContent>
    </DialogPositioner>
  </DialogRoot>
</template>

// apps/web/src/components/control/control-confirm-dialog.tsx
import { Button, Dialog, Portal } from "@chakra-ui/react";
import { resolveConfirmAction, useConfirmActionStore } from "@/stores/control-confirm-action.store";

export function ControlConfirmDialog() {
  const { open, title, message, confirmLabel, cancelLabel } = useConfirmActionStore();

  return (
    <Dialog.Root size="sm" open={open} role="alertdialog">
      <Portal>
        <Dialog.Backdrop />
        <Dialog.Positioner>
          <Dialog.Content>
            <Dialog.Header>
              <Dialog.Title>{title}</Dialog.Title>
            </Dialog.Header>
            <Dialog.Body>{message}</Dialog.Body>
            <Dialog.Footer gap="3">
              <Dialog.ActionTrigger asChild>
                <Button variant="outline" onClick={() => resolveConfirmAction(false)}>
                  {cancelLabel}
                </Button>
              </Dialog.ActionTrigger>
              <Button colorPalette="red" onClick={() => resolveConfirmAction(true)}>
                {confirmLabel}
              </Button>
            </Dialog.Footer>
          </Dialog.Content>
        </Dialog.Positioner>
      </Portal>
    </Dialog.Root>
  );
}
