// apps/web-vue/src/features/control/import-show-panel.vue
<script setup lang="ts">
import { FileUpload } from "@ark-ui/vue";
import { css } from "@styled-system/css";
import { button, fileUpload, input } from "@styled-system/recipes";
import { FILE_EXTENSION } from "@tgb-resolver/realtime";
import { ref } from "vue";

import { useImportShowMutation } from "@/features/control/composables/use-show";
import type { FloatingPanelHandle } from "@/features/control/floating-panel-types";
import { toaster } from "@/features/shared/ui/toaster";

const props = defineProps<{
  panel: FloatingPanelHandle;
}>();

const file = ref<File | null>(null);
const excludedUsernames = ref("");
const importShow = useImportShowMutation();

const fileUploadClasses = fileUpload();
const inputClasses = input({ size: "sm" });

const root = css({ display: "flex", flexDirection: "column", gap: "4", alignItems: "stretch" });
const triggerRow = css({ display: "flex", gap: "2", marginTop: "2" });
const field = css({ display: "flex", flexDirection: "column", gap: "1" });
const fieldLabel = css({ fontSize: "sm", fontWeight: "medium" });
const helper = css({ fontSize: "xs", color: "fg.muted" });
const errorText = css({ color: "fg.error", fontSize: "sm" });
const actions = css({ display: "flex", justifyContent: "flex-end", gap: "2", marginTop: "4" });

function errorMessage(error: unknown): string {
  if (error instanceof Error) return error.message;
  if (typeof error === "string") return error;
  if (error && typeof error === "object") {
    const body = error as { message?: unknown; errors?: Record<string, unknown> };
    const general = body.errors?.generalErrors ?? body.errors?.General;
    if (Array.isArray(general) && typeof general[0] === "string") return general[0];
    if (typeof body.message === "string" && body.message.length > 0) return body.message;
  }
  return "Unknown error";
}

async function accept() {
  if (!file.value) return;

  try {
    await importShow.mutateAsync({
      file: file.value,
      excludedUsernames: excludedUsernames.value
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean),
    });
    props.panel.close(true);
  } catch (error) {
    toaster.create({
      title: "Import failed",
      description: errorMessage(error),
      type: "error",
    });
  }
}
</script>

<template>
  <div :class="root">
    <FileUpload.Root
      :accept="`.xml,${FILE_EXTENSION}`"
      :maxFiles="1"
      :class="fileUploadClasses.root"
      @file-change="(details: { acceptedFiles: File[] }) => {
        const f = details.acceptedFiles[0] ?? null;
        file = f;
        panel.setDirty(Boolean(f) || excludedUsernames.length > 0);
      }"
    >
      <FileUpload.HiddenInput />
      <FileUpload.Label :class="fileUploadClasses.label">Show file</FileUpload.Label>
      <div :class="triggerRow">
        <FileUpload.Trigger asChild>
          <button type="button" :class="button({ variant: 'outline', size: 'sm' })">
            {{ file ? file.name : "Choose file for upload" }}
          </button>
        </FileUpload.Trigger>
        <FileUpload.ClearTrigger v-if="file" asChild>
          <button type="button" :class="button({ variant: 'ghost', size: 'sm' })">
            Clear
          </button>
        </FileUpload.ClearTrigger>
      </div>
    </FileUpload.Root>

    <div :class="field">
      <span :class="fieldLabel">Excluded usernames</span>
      <input
        v-model="excludedUsernames"
        :class="inputClasses"
        placeholder="team_a, team_b"
        @input="panel.setDirty(Boolean(file) || excludedUsernames.length > 0)"
      />
      <span :class="helper">
        Comma-separated. Applies to XML imports only.
      </span>
    </div>

    <p v-if="importShow.error" :class="errorText">
      {{ errorMessage(importShow.error) }}
    </p>

    <div :class="actions">
      <button type="button" :class="button({ variant: 'outline' })" @click="panel.close(false)">
        Cancel
      </button>
      <button
        type="button"
        :class="button()"
        :disabled="!file || importShow.isPending.value"
        @click="accept"
      >
        Import
      </button>
    </div>
  </div>
</template>

// apps/web/src/components/control/import-show-panel.tsx
import { Button, Field, FileUpload, HStack, Input, Stack, Text } from "@chakra-ui/react";
import { FILE_EXTENSION } from "@tgb-resolver/realtime";
import { useState } from "react";

import { useImportShowMutation } from "@/features/control/hooks";
import { useFloatingPanelStore } from "@/store/floating-panel";

export function ImportShowPanel() {
  const [file, setFile] = useState<File | null>(null);
  const [excludedUsernames, setExcludedUsernames] = useState("");
  const setDirty = useFloatingPanelStore((s) => s.setDirty);
  const closeFloatingPanel = useFloatingPanelStore((s) => s.closeFloatingPanel);
  const importShow = useImportShowMutation();

  const accept = async () => {
    if (!file) return;

    await importShow.mutateAsync({
      file,
      excludedUsernames: excludedUsernames
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean),
    });
    closeFloatingPanel(true);
  };

  return (
    <Stack gap={4}>
      <FileUpload.Root
        accept={`.xml,${FILE_EXTENSION}`}
        maxFiles={1}
        onFileChange={(details) => {
          const f = details.acceptedFiles[0] ?? null;
          setFile(f);
          setDirty(Boolean(f) || excludedUsernames.length > 0);
        }}
      >
        <FileUpload.HiddenInput />
        <FileUpload.Label>Show file</FileUpload.Label>
        <HStack gap={2} mt={2}>
          <FileUpload.Trigger asChild>
            <Button variant="outline" size="sm">
              {file ? file.name : "Choose file for upload"}
            </Button>
          </FileUpload.Trigger>
          {file && (
            <FileUpload.ClearTrigger asChild>
              <Button variant="ghost" size="sm">
                Clear
              </Button>
            </FileUpload.ClearTrigger>
          )}
        </HStack>
      </FileUpload.Root>

      <Field.Root>
        <Field.Label>Excluded usernames</Field.Label>
        <Input
          value={excludedUsernames}
          onChange={(event) => {
            setExcludedUsernames(event.target.value);
            setDirty(Boolean(file) || event.target.value.length > 0);
          }}
          placeholder="team_a, team_b"
        />
        <Field.HelperText>Comma-separated. Applies to XML imports only.</Field.HelperText>
      </Field.Root>

      {importShow.error ? <Text color="fg.error">{importShow.error.message}</Text> : null}

      <HStack justify="end">
        <Button variant="outline" onClick={() => closeFloatingPanel(false)}>
          Cancel
        </Button>
        <Button disabled={!file || importShow.isPending} onClick={() => void accept()}>
          Import
        </Button>
      </HStack>
    </Stack>
  );
}
