// apps/web/src/features/control/timeline/current-event-indicator.vue
<script setup lang="ts">
import { css } from "@styled-system/css";
import { type AnimationPlaybackControls, animate } from "motion";
import { computed, onMounted, onUnmounted, useTemplateRef, watch, watchEffect } from "vue";

import { usePlaybackStore } from "@/features/control/playback-store";
import { useColorModeStore } from "@/stores/color-mode-store";

const props = defineProps<{
  eventId: number;
  durationInSeconds?: number;
}>();

const playback = usePlaybackStore();
const colorModeStore = useColorModeStore();
const bar = useTemplateRef<HTMLElement>("bar");
const warning = useTemplateRef<HTMLElement>("warning");
const root = useTemplateRef<HTMLElement>("root");
let controls: AnimationPlaybackControls[] = [];

const active = computed(
  () =>
    playback.currentEventId === props.eventId ||
    playback.state.activeEventIds.includes(props.eventId),
);

// Active rows read inverted in light mode (matches the React reference).
// Applied imperatively to the parent row so only this leaf re-renders.
watchEffect(() => {
  const rowEl = root.value?.closest<HTMLElement>("[data-event-id]");
  if (!rowEl) return;
  const activeInLightMode = active.value && colorModeStore.colorMode === "light";
  rowEl.style.color = activeInLightMode ? "var(--colors-fg-inverted)" : "";
});

function stop() {
  controls.forEach((control) => {
    control.stop();
  });
  controls = [];
}

function run() {
  stop();
  if (!active.value || !bar.value || !warning.value) return;
  const duration = props.durationInSeconds ?? 0;
  controls = [
    animate(bar.value, { scaleX: [0, 1] }, { duration, ease: "linear" }),
    animate(warning.value, { opacity: [0, 0, 1] }, { duration, ease: "linear" }),
  ];
}

watch(active, run, { flush: "post" });
watch(() => props.durationInSeconds, run, { flush: "post" });
onMounted(run);
onUnmounted(stop);
</script>

<template>
  <div ref="root" :class="css({ position: 'absolute', inset: 0, pointerEvents: 'none' })">
    <div
      v-if="active"
      ref="bar"
      :class="css({ position: 'absolute', inset: 0, transform: 'scaleX(0)', transformOrigin: 'left', bg: 'green.600', zIndex: 0 })"
    >
      <div
        ref="warning"
        :class="css({ position: 'absolute', inset: 0, bg: 'red.500', opacity: 0 })"
      />
    </div>
    <div
      v-if="active"
      :class="css({
        position: 'absolute',
        inset: 0,
        borderWidth: 2,
        borderColor: 'border.success',
        // Drives the shared borderColorPulse keyframe (see panda/keyframes.ts).
        '--pulse-from': '{colors.border.success}',
        '--pulse-to': '{colors.border}',
        animation: 'borderPulse',
        zIndex: 1,
      })"
    />
  </div>
</template>

// apps/web/src/features/control/timeline/CurrentEventIndicator.tsx
import { Box, useToken } from "@chakra-ui/react";
import { keyframes } from "@emotion/react";
import { useComputed, useSignalEffect } from "@preact/signals-react";
import { type AnimationPlaybackControls, animate } from "motion/react";
import { useEffect, useRef } from "react";

import { playbackModel } from "@/features/control/playback-model";

const pulseBorder = keyframes`
  0%, 100% {
    border-color: var(--chakra-colors-border-success);
  }

  50% {
    border-color: var(--chakra-colors-border);
  }
`;

interface CurrentEventIndicatorProps {
  eventId: number;
  durationInSeconds?: number;
}

export function CurrentEventIndicator({ eventId, durationInSeconds }: CurrentEventIndicatorProps) {
  const [success, error] = useToken("colors", ["green.600", "red.500"]);
  const barRef = useRef<HTMLDivElement>(null);
  const warnRef = useRef<HTMLDivElement>(null);
  const animationRef = useRef<AnimationPlaybackControls[]>([]);
  const isCurrent = useComputed(() => playbackModel.currentCueId.value === eventId);

  // The row container's "current" text color (previously driven by an isCurrent
  // prop that re-rendered the whole row subtree on every playback advance) is
  // applied imperatively to the parent row so only this leaf re-renders.
  useSignalEffect(() => {
    const rowEl = barRef.current?.parentElement;
    if (!rowEl) return;
    const currentInLightMode = isCurrent.value && rowEl.closest(".light") !== null;
    rowEl.style.color = currentInLightMode ? "var(--chakra-colors-fg-inverted)" : "";
  });

  useEffect(() => {
    const barEl = barRef.current;
    const warnEl = warnRef.current;
    if (!barEl || !warnEl) return;

    animationRef.current.forEach((controls) => {
      controls.stop();
    });
    animationRef.current = [];

    const duration = durationInSeconds ?? 0;

    if (isCurrent.value) {
      animationRef.current = [
        animate(barEl, { scaleX: [0, 1] }, { duration, ease: "linear" }),
        animate(warnEl, { opacity: [0, 0, 1] }, { duration, ease: "linear" }),
      ];
    } else {
      animationRef.current = [
        animate(barEl, { scaleX: 0 }, { duration: 0 }),
        animate(warnEl, { opacity: 0 }, { duration: 0 }),
      ];
    }

    return () => {
      animationRef.current.forEach((controls) => {
        controls.stop();
      });
    };
  }, [isCurrent.value, durationInSeconds]);

  return (
    <>
      <Box
        ref={barRef}
        position="absolute"
        top={0}
        left={0}
        h="full"
        w="full"
        transform="scaleX(0)"
        transformOrigin="left"
        backgroundColor={success}
        pointerEvents="none"
        zIndex={0}
      >
        <Box ref={warnRef} position="absolute" inset={0} backgroundColor={error} opacity={0} />
      </Box>
      <Box
        data-testid="current-event-border"
        position="absolute"
        inset={0}
        borderWidth={2}
        borderColor={isCurrent.value ? "border.success" : "transparent"}
        animation={isCurrent.value ? `${pulseBorder} 1s infinite` : undefined}
        pointerEvents="none"
        zIndex={1}
      />
    </>
  );
}
