// apps/web/src/features/control/timeline/timeline-table.tsx
import { Box, Center, Spinner, Text } from "@chakra-ui/react";
import { move } from "@dnd-kit/helpers";
import { DragDropProvider } from "@dnd-kit/react";
import { useSortable } from "@dnd-kit/react/sortable";
import { useComputed, useSignalEffect } from "@preact/signals-react";
import { For } from "@preact/signals-react/utils";
import { PlaybackStatus, TimelineEventType } from "@tgb-resolver/contracts";
import type { TimelineEvent, TimelineTableItem } from "@tgb-resolver/realtime";
import { memo, type RefObject, useCallback, useRef } from "react";

import {
  useControlIsLive,
  useControlShowQuery,
  useMoveTimelineEventMutation,
  useSeekPlaybackMutation,
} from "@/features/control/hooks";
import { playbackModel } from "@/features/control/playback-model";
import { animateScrollIntoView } from "@/features/leaderboard/utils/scroll";
import { showModel } from "@/features/shared/show-model";

import { createTimelineReorderState } from "./timeline-reorder-state";
import { TimelineRowContextMenu, useTimelineRowContextMenu } from "./timeline-row-context-menu";
import { ControlTimelineTableHeader, ControlTimelineTableItem } from "./timeline-table-item";

export interface ControlTimelineTableHandle {
  scrollToCurrent: () => void;
}

interface ControlTimelineTableProps {
  apiRef?: { current: ControlTimelineTableHandle | null };
}

const TIMELINE_CONTAINER_CSS = {
  "& [data-timeline-row]:nth-of-type(odd) [data-event-id]": { bg: "bg" },
  "& [data-timeline-row]:nth-of-type(even) [data-event-id]": { bg: "bg.emphasized" },
};

function scrollEventToTop(parent: HTMLDivElement | null, currentEventId: number | null) {
  if (!parent || currentEventId == null) return;
  const el = parent.querySelector<HTMLElement>(`[data-event-id="${currentEventId}"]`);
  if (!el) return;
  animateScrollIntoView(el, parent, { block: "start", duration: 0.15 });
}

export function ControlTimelineTable({ apiRef }: ControlTimelineTableProps) {
  const showQuery = useControlShowQuery();
  const orderedIds = showModel.showOrderedIds.value;
  const isLive = useControlIsLive();
  const seekPlayback = useSeekPlaybackMutation();
  const moveEvent = useMoveTimelineEventMutation();
  const timelineContextMenu = useTimelineRowContextMenu();

  const seekRef = useRef(seekPlayback.mutate);
  seekRef.current = seekPlayback.mutate;
  const onSeek = useCallback((id: number) => {
    // Seeking is only meaningful while playing or paused (an idle timeline
    // cannot resume). Guarding here keeps row-click seeking consistent with
    // the transport controls.
    const status = playbackModel.status.value;
    if (status !== PlaybackStatus.RUNNING && status !== PlaybackStatus.PAUSED) return;
    seekRef.current(id);
  }, []);

  const openContextMenuRef = useRef(timelineContextMenu.open);
  openContextMenuRef.current = timelineContextMenu.open;
  const onOpenContextMenu = useCallback(
    (e: React.MouseEvent, payload: TimelineTableItem) => openContextMenuRef.current(e, payload),
    [],
  );

  const parentRef = useRef<HTMLDivElement>(null);
  const movePendingRef = useRef(false);
  const moveEventRef = useRef(moveEvent.mutate);
  moveEventRef.current = moveEvent.mutate;
  const reorderSnapshotRef =
    useRef<ReturnType<typeof showModel.optimisticallyReorderTimeline>>(null);

  const commitReorder = useCallback((orderedIds: number[]) => {
    const initialOrderedIds = showModel.showOrderedIds.peek();
    // Find the row that changed position
    let movedItem: TimelineEvent | null = null;
    let targetIndex = -1;

    for (let i = 0; i < orderedIds.length; i++) {
      if (orderedIds[i] !== initialOrderedIds[i]) {
        // Check if this item is a CUS event (only CUS events can be moved)
        const event = showModel.showEvents.peek()[orderedIds[i]];
        if (event?.type === TimelineEventType.CUS) {
          movedItem = event;
          targetIndex = i;
          break;
        }
      }
    }

    if (!movedItem || targetIndex < 0) return;

    // Determine relative destination
    const before = targetIndex === 0;
    const relativeToEventId = before ? orderedIds[1] : orderedIds[targetIndex - 1];

    if (relativeToEventId != null) {
      const snapshot = showModel.optimisticallyReorderTimeline(orderedIds);
      const expectedOrderedIds = showModel.showOrderedIds.peek();
      reorderSnapshotRef.current = snapshot;
      movePendingRef.current = true;
      moveEventRef.current(
        {
          eventId: movedItem.id,
          relativeToEventId,
          before,
        },
        {
          onError: () => {
            const snapshot = reorderSnapshotRef.current;
            if (snapshot) {
              showModel.restoreTimelineOrderIfCurrent(snapshot, expectedOrderedIds);
            }
          },
          onSettled: () => {
            reorderSnapshotRef.current = null;
            movePendingRef.current = false;
          },
        },
      );
    }
  }, []);

  if (apiRef) {
    apiRef.current = {
      scrollToCurrent: () => {
        scrollEventToTop(parentRef.current, playbackModel.currentCueId.peek());
      },
    };
  }

  if (showQuery.isLoading) {
    return (
      <Center boxSize="full">
        <Spinner />
      </Center>
    );
  }

  if (showQuery.error) {
    return (
      <Center boxSize="full" px={4}>
        <Text>{showQuery.error.message}</Text>
      </Center>
    );
  }

  if (orderedIds.length === 0) {
    return (
      <Center boxSize="full">
        <Text>No show loaded.</Text>
      </Center>
    );
  }

  return (
    <Box boxSize="full" display="flex" flexDir="column" minH={0} overflow="hidden">
      <ControlTimelineTableHeader isLive={isLive} />

      <Box flex={1} minH={0} ref={parentRef} overflow="auto" css={TIMELINE_CONTAINER_CSS}>
        <CurrentEventScroller parentRef={parentRef} />
        <TimelineReorderList
          orderedIds={orderedIds}
          isLive={isLive}
          onSeek={onSeek}
          onOpenContextMenu={onOpenContextMenu}
          onCommitReorder={commitReorder}
          isMovePending={movePendingRef}
        />
      </Box>
      <TimelineRowContextMenu
        state={timelineContextMenu.state}
        onClose={timelineContextMenu.close}
      />
    </Box>
  );
}

type DragOverHandler = NonNullable<React.ComponentProps<typeof DragDropProvider>["onDragOver"]>;
type DragEndHandler = NonNullable<React.ComponentProps<typeof DragDropProvider>["onDragEnd"]>;

const TimelineReorderList = memo(function TimelineReorderList({
  orderedIds,
  isLive,
  onSeek,
  onOpenContextMenu,
  onCommitReorder,
  isMovePending,
}: {
  orderedIds: number[];
  isLive: boolean;
  onSeek: (id: number) => void;
  onOpenContextMenu: (e: React.MouseEvent, payload: TimelineTableItem) => void;
  onCommitReorder: (orderedIds: number[]) => void;
  isMovePending: RefObject<boolean>;
}) {
  const reorderStateRef = useRef<ReturnType<typeof createTimelineReorderState>>(null);
  if (!isLive && !reorderStateRef.current) reorderStateRef.current = createTimelineReorderState();
  // The reorder state is lazily created above and is non-null on every
  // edit-mode render; the `?.` only guards live mode, which never initializes it.
  const displayIds = reorderStateRef.current?.rows.value ?? orderedIds;
  const onCommitReorderRef = useRef(onCommitReorder);
  onCommitReorderRef.current = onCommitReorder;
  // Latest committed order, for the drag handlers (stable across renders).
  const orderedIdsRef = useRef(orderedIds);
  orderedIdsRef.current = orderedIds;

  const commitDrag = useCallback(() => {
    const nextRows = reorderStateRef.current?.take();
    if (nextRows && !isMovePending.current) onCommitReorderRef.current(nextRows);
  }, [isMovePending]);

  // The provisional order currently shown (dragging) or the committed base.
  const currentDisplay = useCallback(
    () => reorderStateRef.current?.rows.value ?? orderedIdsRef.current,
    [],
  );

  const onDragOver = useCallback<DragOverHandler>(
    (event) => {
      if (event.operation.canceled || isMovePending.current) return;
      reorderStateRef.current?.set(move(currentDisplay(), event));
    },
    [currentDisplay, isMovePending],
  );

  const onDragEnd = useCallback<DragEndHandler>(
    (event) => {
      if (isMovePending.current) return;
      if (event.operation.canceled || event.operation.target == null) {
        // Esc/dropped outside any row: discard the provisional order.
        reorderStateRef.current?.take();
        return;
      }
      reorderStateRef.current?.set(move(currentDisplay(), event));
      commitDrag();
    },
    [currentDisplay, commitDrag, isMovePending],
  );

  if (isLive) {
    // Drop any uncommitted drag order when leaving edit mode so it cannot
    // resurface if the user toggles back.
    reorderStateRef.current?.take();
    return (
      <Box as="ul" style={{ listStyle: "none", padding: 0, margin: 0 }}>
        <For each={orderedIds}>
          {(eventId) => (
            <TimelineStaticRow
              key={eventId}
              eventId={eventId}
              isLive={isLive}
              onSeek={onSeek}
              onOpenContextMenu={onOpenContextMenu}
            />
          )}
        </For>
      </Box>
    );
  }

  return (
    <Box as="ul" style={{ listStyle: "none", padding: 0, margin: 0 }}>
      <DragDropProvider onDragOver={onDragOver} onDragEnd={onDragEnd}>
        {displayIds.map((eventId, index) => (
          <TimelineRowItem
            key={eventId}
            eventId={eventId}
            index={index}
            isLive={isLive}
            onSeek={onSeek}
            onOpenContextMenu={onOpenContextMenu}
          />
        ))}
      </DragDropProvider>
    </Box>
  );
});

const TimelineRowItem = memo(function TimelineRowItem({
  eventId,
  index,
  isLive,
  onSeek,
  onOpenContextMenu,
}: {
  eventId: number;
  index: number;
  isLive: boolean;
  onSeek: (id: number) => void;
  onOpenContextMenu: (e: React.MouseEvent, payload: TimelineTableItem) => void;
}) {
  const payload = useComputed(() => showModel.timelineItemsById.value[eventId]);
  const isReorderable = payload.value?.type === TimelineEventType.CUS && !isLive;
  const { ref, handleRef } = useSortable({
    id: eventId,
    index,
    disabled: { draggable: !isReorderable },
  });

  if (!payload.value) return null;

  return (
    <li ref={ref} data-timeline-row style={{ position: "relative", userSelect: "none" }}>
      <ControlTimelineTableItem
        payload={payload.value}
        isLive={isLive}
        onSeek={onSeek}
        onOpenContextMenu={onOpenContextMenu}
        dragHandleRef={isReorderable ? handleRef : undefined}
      />
    </li>
  );
});

const TimelineStaticRow = memo(function TimelineStaticRow({
  eventId,
  isLive,
  onSeek,
  onOpenContextMenu,
}: {
  eventId: number;
  isLive: boolean;
  onSeek: (id: number) => void;
  onOpenContextMenu: (e: React.MouseEvent, payload: TimelineTableItem) => void;
}) {
  const payload = useComputed(() => showModel.timelineItemsById.value[eventId]);

  if (!payload.value) return null;

  return (
    <li data-timeline-row>
      <ControlTimelineTableItem
        payload={payload.value}
        isLive={isLive}
        onSeek={onSeek}
        onOpenContextMenu={onOpenContextMenu}
      />
    </li>
  );
});

function CurrentEventScroller({ parentRef }: { parentRef: RefObject<HTMLDivElement | null> }) {
  // useSignalEffect (a React hook) re-runs whenever the tracked signals change —
  // unlike a bare .value read inside a null-returning component, which the
  // @preact/signals-react babel transform does not instrument, so the scroll
  // would otherwise never fire after the initial mount.
  useSignalEffect(() => {
    const target = playbackModel.currentCueId.value;
    // Only scroll when the current event starts a new concurrent group (or is
    // standalone). Offset children of an already-visible group fire while the
    // group is in view — scrolling to them would yank the timeline away from
    // the group's parent.
    if (target != null && showModel.timelineItemsById.value[target]?.triggerOffsetSeconds != null) {
      return;
    }
    const raf = requestAnimationFrame(() => scrollEventToTop(parentRef.current, target));
    return () => cancelAnimationFrame(raf);
  });

  return null;
}

// apps/web/src/features/control/timeline/timeline-table.vue
<script setup lang="ts">
import { move } from "@dnd-kit/helpers";
import { DragDropProvider, type DragEndEvent, type DragOverEvent } from "@dnd-kit/vue";
import { css } from "@styled-system/css";
import { PlaybackStatus, TimelineEventType } from "@tgb-resolver/contracts";
import type { TimelineTableItem as TimelineRowPayload } from "@tgb-resolver/realtime";
import { computed, nextTick, onMounted, ref, useTemplateRef, watch } from "vue";

import { useControlIsLive, useControlShowQuery, useMoveTimelineEventMutation, useSeekPlaybackMutation } from "@/features/control/composables/use-show";
import { usePlaybackStore } from "@/features/control/playback-store";
import { animateScrollIntoView } from "@/features/leaderboard/utils/scroll";
import Spinner from "@/features/shared/ui/spinner.vue";
import { useShowStore } from "@/stores/show-store";

import TimelineContextMenu from "./timeline-context-menu.vue";
import { createTimelineReorderState } from "./timeline-reorder-state";
import TimelineSortableRow from "./timeline-sortable-row.vue";
import TimelineTableHeader from "./timeline-table-header.vue";

const showQuery = useControlShowQuery();
const showStore = useShowStore();
const playback = usePlaybackStore();
const isLive = useControlIsLive();
const seekPlayback = useSeekPlaybackMutation();
const moveEvent = useMoveTimelineEventMutation();

const containerRef = useTemplateRef<HTMLElement>("containerRef");
const contextTarget = ref<{ payload: TimelineRowPayload; x: number; y: number } | null>(null);
const reorderState = createTimelineReorderState();

const displayIds = computed(() => (isLive.value ? showStore.showOrderedIds : (reorderState.rows.value ?? showStore.showOrderedIds)));
const displayRows = computed(() =>
  displayIds.value
    .map((id) => showStore.timelineItemsById[id])
    .filter((row): row is TimelineRowPayload => row !== undefined),
);

function onSeek(id: number) {
  const status = playback.status;
  if (status !== PlaybackStatus.RUNNING && status !== PlaybackStatus.PAUSED) return;
  seekPlayback.mutate(id);
}

function scrollEventToTop(eventId: number | null) {
  if (!containerRef.value || eventId == null) return;
  const el = containerRef.value.querySelector<HTMLElement>(`[data-event-id="${eventId}"]`);
  if (!el) return;
  animateScrollIntoView(el, containerRef.value, { block: "start", duration: 0.15 });
}

function scrollToCurrent() {
  scrollEventToTop(playback.currentCueId);
}

defineExpose({
  scrollToCurrent,
});

// Scroll to the current event on mount. The rows may not exist yet while the
// query is loading, so also fire once when the first row renders.
let hasScrolledOnMount = false;
function scrollToCurrentOnMount() {
  if (hasScrolledOnMount || displayRows.value.length === 0) return;
  hasScrolledOnMount = true;
  void nextTick(() => requestAnimationFrame(scrollToCurrent));
}

onMounted(scrollToCurrentOnMount);
watch(
  () => displayRows.value.length > 0,
  (hasRows) => {
    if (hasRows) scrollToCurrentOnMount();
  },
);

watch(
  () => playback.currentCueId,
  (target) => {
    if (target != null && showStore.timelineItemsById[target]?.triggerOffsetSeconds != null) {
      return;
    }
    requestAnimationFrame(() => scrollEventToTop(target));
  },
);

// --- Reorder wiring, ported 1:1 from the React reference (timeline-table.tsx
// :: TimelineReorderList + commitReorder). DragOver keeps a provisional order;
// DragEnd commits it as a single move mutation with optimistic apply/revert.

type ReorderSnapshot = ReturnType<typeof showStore.optimisticallyReorderTimeline>;

function currentDisplay(): number[] {
  return reorderState.rows.value ?? showStore.showOrderedIds;
}

const isMovePending = computed(() => moveEvent.isPending.value);

let reorderSnapshot: ReorderSnapshot | null = null;

function onDragOver(event: DragOverEvent) {
  if (event.operation.canceled || isMovePending.value) return;
  reorderState.set(move(currentDisplay(), event));
}

function onDragEnd(event: DragEndEvent) {
  if (isMovePending.value) return;
  if (event.operation.canceled || event.operation.target == null) {
    // Esc / dropped outside any row: discard the provisional order.
    reorderState.take();
    return;
  }
  reorderState.set(move(currentDisplay(), event));
  commitReorder();
}

function commitReorder() {
  const nextRows = reorderState.take();
  if (!nextRows || isMovePending.value) return;

  // Find the row whose position changed; only CUS events are movable.
  const initialOrderedIds = showStore.showOrderedIds;
  let movedEventId: number | null = null;
  let targetIndex = -1;
  for (let i = 0; i < nextRows.length; i++) {
    const id = nextRows[i];
    if (id === undefined || id === initialOrderedIds[i]) continue;
    const event = showStore.showEvents[id];
    if (event?.type === TimelineEventType.CUS) {
      movedEventId = id;
      targetIndex = i;
      break;
    }
  }
  if (movedEventId == null || targetIndex < 0) return;

  const before = targetIndex === 0;
  const relativeToEventId = before ? nextRows[1] : nextRows[targetIndex - 1];
  if (relativeToEventId == null) return;

  const snapshot = showStore.optimisticallyReorderTimeline(nextRows);
  const expectedOrderedIds = showStore.showOrderedIds;
  reorderSnapshot = snapshot;
  moveEvent.mutate(
    { eventId: movedEventId, relativeToEventId, before },
    {
      onError: () => {
        if (reorderSnapshot) {
          showStore.restoreTimelineOrderIfCurrent(reorderSnapshot, expectedOrderedIds);
        }
      },
      onSettled: () => {
        reorderSnapshot = null;
      },
    },
  );
}

function openContextMenu(event: MouseEvent, payload: TimelineRowPayload) {
  event.preventDefault();
  event.stopPropagation();
  contextTarget.value = {
    payload,
    x: Math.max(8, Math.min(event.clientX, window.innerWidth - 180)),
    y: Math.max(8, Math.min(event.clientY, window.innerHeight - 110)),
  };
}
</script>

<template>
  <div
    v-if="showQuery.isLoading.value"
    :class="css({ display: 'flex', alignItems: 'center', justifyContent: 'center', boxSize: 'full' })"
  >
    <Spinner size="lg" label="" aria-hidden="true" />
  </div>

  <div
    v-else-if="showQuery.error.value"
    :class="css({ display: 'flex', alignItems: 'center', justifyContent: 'center', boxSize: 'full', px: 4 })"
  >
    <p>{{ showQuery.error.value.message }}</p>
  </div>

  <div
    v-else-if="displayIds.length === 0"
    :class="css({ display: 'flex', alignItems: 'center', justifyContent: 'center', boxSize: 'full' })"
  >
    <p>No show loaded.</p>
  </div>

  <div
    v-else
    :class="css({ boxSize: 'full', display: 'flex', flexDirection: 'column', minH: 0, overflow: 'hidden' })"
  >
    <TimelineTableHeader :is-live="isLive" />

    <div
      ref="containerRef"
      :class="css({
        flex: 1,
        minH: 0,
        overflow: 'auto',
        '& [data-timeline-row]:nth-of-type(odd) [data-event-id]': { bg: 'bg' },
        '& [data-timeline-row]:nth-of-type(even) [data-event-id]': { bg: 'bg.emphasized' },
      })"
    >
      <div :class="css({ w: 'full', display: 'flex', flexDirection: 'column', alignItems: 'stretch' })">
        <template v-if="displayIds.length > 0">
          <DragDropProvider v-if="!isLive" @drag-over="onDragOver" @drag-end="onDragEnd">
            <TimelineSortableRow
              v-for="(row, index) in displayRows"
              :key="row.id"
              :payload="row"
              :index="index"
              :is-live="isLive"
              @seek="onSeek"
              @contextmenu="openContextMenu"
            />
          </DragDropProvider>
          <!-- Live mode renders a static list: no dnd context, no sortable wiring -->
          <template v-else>
            <TimelineSortableRow
              v-for="(row, index) in displayRows"
              :key="row.id"
              :payload="row"
              :index="index"
              :is-live="isLive"
              @seek="onSeek"
              @contextmenu="openContextMenu"
            />
          </template>
        </template>
      </div>
    </div>

    <TimelineContextMenu
      v-if="contextTarget"
      :target="contextTarget.payload"
      :x="contextTarget.x"
      :y="contextTarget.y"
      @close="contextTarget = null"
    />
  </div>
</template>
