// apps/web/src/features/control/timeline/timeline-number-editable.vue
<script setup lang="ts">
import type { TimelineTableItem } from "@tgb-resolver/realtime";
import { computed } from "vue";

import { usePatchTimelineEventMutation } from "@/features/control/composables/use-show";

import TimelineCellEditable from "./timeline-cell-editable.vue";

const props = defineProps<{
  payload: TimelineTableItem;
  field: "durationSeconds" | "triggerOffsetSeconds";
}>();

const patchEvent = usePatchTimelineEventMutation();
const current = computed(() => props.payload[props.field]);

// Only the trigger offset shows an explicit sign on preview; durations are
// always non-negative and read as-is.
const displayValue = computed(() => {
  const val = current.value;
  if (val == null) return "";
  return props.field === "triggerOffsetSeconds" && val > 0 ? `+${val}` : String(val);
});

function handleBlankCommit() {
  patchEvent.mutate({
    eventId: props.payload.id,
    ...(props.field === "durationSeconds"
      ? { useDefaultDuration: true }
      : { clearTriggerOffset: true }),
  });
}

function handleCommit(value: string) {
  const normalizedValue = value.trim();
  const next = Number(normalizedValue);
  if (
    Number.isFinite(next) &&
    (props.field !== "durationSeconds" || next >= 0) &&
    next !== current.value
  ) {
    patchEvent.mutate({ eventId: props.payload.id, [props.field]: next });
  }
}
</script>

<template>
  <TimelineCellEditable
    :value="current == null ? '' : String(current)"
    :display-value="displayValue"
    text-align="end"
    font-family="mono"
    @commit="handleCommit"
    @blank-commit="handleBlankCommit"
  />
</template>

// apps/web/src/features/control/timeline/timeline-number-editable.tsx
import type { TimelineTableItem } from "@tgb-resolver/realtime";
import { useCallback } from "react";

import { usePatchTimelineEventMutation } from "@/features/control/hooks";

import { TimelineCellEditable } from "./timeline-cell-editable";

export interface ControlTimelineNumberEditableProps {
  payload: TimelineTableItem;
  field: "durationSeconds" | "triggerOffsetSeconds";
}

export function ControlTimelineNumberEditable({
  payload,
  field,
}: ControlTimelineNumberEditableProps) {
  const patchEvent = usePatchTimelineEventMutation();
  const current = payload[field];

  const handleBlankCommit = useCallback(() => {
    void patchEvent.mutateAsync({
      eventId: payload.id,
      ...(field === "durationSeconds"
        ? { useDefaultDuration: true }
        : { clearTriggerOffset: true }),
    });
  }, [field, patchEvent.mutateAsync, payload.id]);

  const handleCommit = useCallback(
    (value: string) => {
      const normalizedValue = value.trim();
      const next = Number(normalizedValue);
      if (Number.isFinite(next) && (field !== "durationSeconds" || next >= 0) && next !== current)
        void patchEvent.mutateAsync({ eventId: payload.id, [field]: next });
    },
    [current, field, patchEvent.mutateAsync, payload.id],
  );

  return (
    <TimelineCellEditable
      value={current == null ? "" : String(current)}
      displayValue={
        field === "triggerOffsetSeconds" && current != null && current > 0
          ? `+${current}`
          : (current ?? "")
      }
      onBlankCommit={handleBlankCommit}
      textAlign="end"
      fontFamily="mono"
      onCommit={handleCommit}
    />
  );
}
