// apps/web/src/features/control/timeline/timeline-custom-name-editable.vue
<script setup lang="ts">
import type { TimelineTableItem } from "@tgb-resolver/realtime";
import { computed } from "vue";

import { useRenameControlEventMutation } from "@/features/control/composables/use-show";

import TimelineCellEditable from "./timeline-cell-editable.vue";

const props = defineProps<{
  payload: TimelineTableItem;
}>();

const renameEvent = useRenameControlEventMutation();
const currentName = computed(() => props.payload.customName ?? "");

function resolveDisplayName(payload: Pick<TimelineTableItem, "customName" | "placeholderName">) {
  return payload.customName && payload.customName.trim().length > 0
    ? payload.customName
    : payload.placeholderName;
}

function handleCommit(value: string) {
  const customName = value.trim();
  if (customName !== currentName.value.trim()) {
    renameEvent.mutate({ eventId: props.payload.id, type: props.payload.type, customName });
  }
}
</script>

<template>
  <TimelineCellEditable
    :value="currentName"
    :display-value="resolveDisplayName(payload)"
    :placeholder="payload.placeholderName"
    text-align="start"
    @commit="handleCommit"
  />
</template>

// apps/web/src/features/control/timeline/timeline-custom-name-editable.tsx
import type { TimelineTableItem } from "@tgb-resolver/realtime";
import { memo, useCallback } from "react";

import { useRenameControlEventMutation } from "@/features/control/hooks";

import { TimelineCellEditable } from "./timeline-cell-editable";

export interface ControlTimelineEventCustomNameEditableProps {
  payload: TimelineTableItem;
}

function resolveDisplayName(payload: Pick<TimelineTableItem, "customName" | "placeholderName">) {
  return payload.customName && payload.customName.trim().length > 0
    ? payload.customName
    : payload.placeholderName;
}

export const ControlTimelineEventCustomNameEditable = memo(
  function ControlTimelineEventCustomNameEditable({
    payload,
  }: ControlTimelineEventCustomNameEditableProps) {
    const renameEvent = useRenameControlEventMutation();
    const currentName = payload.customName ?? "";

    const handleCommit = useCallback(
      (value: string) => {
        const customName = value.trim();
        if (customName !== currentName.trim()) {
          void renameEvent.mutateAsync({ eventId: payload.id, type: payload.type, customName });
        }
      },
      [currentName, payload.id, payload.type, renameEvent.mutateAsync],
    );

    return (
      <TimelineCellEditable
        value={currentName}
        displayValue={resolveDisplayName(payload)}
        placeholder={payload.placeholderName}
        textAlign="start"
        onCommit={handleCommit}
      />
    );
  },
);
