// apps/web/src/components/control/panels/main/tabs/control-main-info-tab.tsx
import { Box, Button, Code, Heading, HStack, Text, VStack } from "@chakra-ui/react";
import { ShowMode } from "@tgb-resolver/realtime";

import {
  dataVersion,
  showEvents,
  showMeta,
  showMode,
  showOrderedIds,
} from "@/features/control/show-store";
import { floatingPanelModel } from "@/models/floating-panel";
import { FloatingPanelType } from "@/models/floating-panel-types";

export function ControlMainInfoTab() {
  const mode = showMode.value;
  const events = showEvents.value;
  const meta = showMeta.value;

  return (
    <Box boxSize="full" p={4}>
      <VStack gap={4} align="stretch">
        <Box>
          <HStack justify="space-between" mb={2}>
            <Heading size="md">Show Details</Heading>
            <Button
              size="sm"
              variant="outline"
              onClick={() =>
                void floatingPanelModel.openFloatingPanel(
                  FloatingPanelType.InspectShow,
                  "Inspect show",
                )
              }
            >
              Inspect
            </Button>
          </HStack>
        </Box>

        <VStack gap={2} align="stretch">
          <Box>
            <Text fontSize="sm" color="fg.muted">
              Mode
            </Text>
            <Text fontFamily="mono" fontSize="md">
              {mode === ShowMode.EDITING ? "Editing" : mode === ShowMode.LIVE ? "Live" : "Unknown"}
            </Text>
          </Box>

          {events.size > 0 && (
            <Box>
              <Text fontSize="sm" color="fg.muted">
                Timeline
              </Text>
              <Text fontFamily="mono" fontSize="md">
                {events.size} event{events.size !== 1 ? "s" : ""} | {showOrderedIds.value.length}{" "}
                ordered
              </Text>
            </Box>
          )}

          {meta && (
            <Box>
              <Text fontSize="sm" color="fg.muted">
                Metadata
              </Text>
              <Code display="block" whiteSpace="pre-wrap" p={2}>
                {JSON.stringify(meta, null, 2)}
              </Code>
            </Box>
          )}

          <Box>
            <Text fontSize="sm" color="fg.muted">
              Version
            </Text>
            <Text fontFamily="mono" fontSize="md">
              {dataVersion.value}
            </Text>
          </Box>
        </VStack>
      </VStack>
    </Box>
  );
}

// apps/web/src/features/control/panels/main/tabs/control-main-info-tab.vue
<script setup lang="ts">
import { css, cx } from "@styled-system/css";
import { button, code, heading } from "@styled-system/recipes";
import { ShowMode } from "@tgb-resolver/realtime";
import { computed } from "vue";

import { useFloatingPanelStore } from "@/features/control/floating-panel-store";
import { FloatingPanelType } from "@/features/control/floating-panel-types";
import { useShowStore } from "@/stores/show-store";

const showStore = useShowStore();
const floatingPanelStore = useFloatingPanelStore();

const mode = computed(() => showStore.showMode);
const events = computed(() => showStore.showEvents);
const meta = computed(() => showStore.showMeta);
const orderedIds = computed(() => showStore.showOrderedIds);
const dataVersion = computed(() => showStore.dataVersion);
const eventsCount = computed(() => Object.keys(events.value).length);
</script>

<template>
  <div :class="css({ h: 'full', p: '4', overflow: 'auto' })">
    <div :class="css({ display: 'flex', flexDirection: 'column', gap: '4', alignItems: 'stretch' })">
      <div>
        <div :class="css({ display: 'flex', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', mb: '2' })">
          <h2 :class="cx(heading({ size: 'md' }), css({ color: 'colorPalette.fg', fontWeight: 700, lineHeight: 1.2, marginBlock: 0 }))">
            Show Details
          </h2>
          <button
            type="button"
            :class="button({ size: 'sm', variant: 'outline' })"
            @click="floatingPanelStore.openFloatingPanel(FloatingPanelType.InspectShow, 'Inspect show')"
          >
            Inspect
          </button>
        </div>
      </div>

      <div :class="css({ display: 'flex', flexDirection: 'column', gap: '2', alignItems: 'stretch' })">
        <div>
          <div :class="css({ fontSize: 'sm', color: 'fg.muted' })">Mode</div>
          <div :class="css({ fontFamily: 'mono', fontSize: 'md' })">
            {{ mode === ShowMode.EDITING ? "Editing" : mode === ShowMode.LIVE ? "Live" : "Unknown" }}
          </div>
        </div>

        <div v-if="eventsCount > 0">
          <div :class="css({ fontSize: 'sm', color: 'fg.muted' })">Timeline</div>
          <div :class="css({ fontFamily: 'mono', fontSize: 'md' })">
            {{ eventsCount }} event{{ eventsCount !== 1 ? "s" : "" }} | {{ orderedIds.length }} ordered
          </div>
        </div>

        <div v-if="meta">
          <div :class="css({ fontSize: 'sm', color: 'fg.muted' })">Metadata</div>
          <code :class="cx(code(), css({ display: 'block', whiteSpace: 'pre-wrap', p: 2 }))">
            {{ JSON.stringify(meta, null, 2) }}
          </code>
        </div>

        <div>
          <div :class="css({ fontSize: 'sm', color: 'fg.muted' })">Version</div>
          <div :class="css({ fontFamily: 'mono', fontSize: 'md' })">
            {{ dataVersion }}
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
