// apps/web-vue/src/features/control/panels/main/tabs/control-main-info-tab.vue
<script setup lang="ts">
import { Box, HStack, VStack } from "@styled-system/jsx";
import { ShowMode } from "@tgb-resolver/realtime";
import { computed } from "vue";

import { useFloatingPanelStore } from "@/features/control/floating-panel-store";
import { FloatingPanelType } from "@/features/control/floating-panel-types";
import Button from "@/features/shared/ui/button.vue";
import Heading from "@/features/shared/ui/heading.vue";
import { useShowStore } from "@/stores/show-store";

const showStore = useShowStore();
const floatingPanelStore = useFloatingPanelStore();

const mode = computed(() => showStore.showMode);
const events = computed(() => showStore.showEvents);
const meta = computed(() => showStore.showMeta);
const orderedIds = computed(() => showStore.showOrderedIds);
const dataVersion = computed(() => showStore.dataVersion);
const eventsCount = computed(() => Object.keys(events.value).length);
</script>

<template>
  <Box h="full" p="4" overflow="auto">
    <VStack gap="4" alignItems="stretch">
      <Box>
        <HStack justifyContent="space-between" mb="2">
          <Heading size="md">Show Details</Heading>
          <Button
            size="sm"
            variant="outline"
            @click="floatingPanelStore.openFloatingPanel(FloatingPanelType.InspectShow, 'Inspect show')"
          >
            Inspect
          </Button>
        </HStack>
      </Box>

      <VStack gap="2" alignItems="stretch">
        <Box>
          <Box fontSize="sm" color="fg.muted">Mode</Box>
          <Box fontFamily="mono" fontSize="md">
            {{ mode === ShowMode.EDITING ? "Editing" : mode === ShowMode.LIVE ? "Live" : "Unknown" }}
          </Box>
        </Box>

        <Box v-if="eventsCount > 0">
          <Box fontSize="sm" color="fg.muted">Timeline</Box>
          <Box fontFamily="mono" fontSize="md">
            {{ eventsCount }} event{{ eventsCount !== 1 ? "s" : "" }} | {{ orderedIds.length }} ordered
          </Box>
        </Box>

        <Box v-if="meta">
          <Box fontSize="sm" color="fg.muted">Metadata</Box>
          <Box
            as="pre"
            fontFamily="mono"
            fontSize="xs"
            whiteSpace="pre-wrap"
            p="2"
            bg="bg.muted"
            rounded="md"
          >
            {{ JSON.stringify(meta, null, 2) }}
          </Box>
        </Box>

        <Box>
          <Box fontSize="sm" color="fg.muted">Version</Box>
          <Box fontFamily="mono" fontSize="md">
            {{ dataVersion }}
          </Box>
        </Box>
      </VStack>
    </VStack>
  </Box>
</template>

// apps/web/src/features/control/panels/main/tabs/control-main-info-tab.tsx
import { Box, Button, Code, Heading, HStack, Text, VStack } from "@chakra-ui/react";
import { ShowMode } from "@tgb-resolver/realtime";

import { floatingPanelModel } from "@/features/control/floating-panel-model";
import { FloatingPanelType } from "@/features/control/floating-panel-types";
import { showModel } from "@/features/shared/show-model";

export function ControlMainInfoTab() {
  const mode = showModel.showMode.value;
  const events = showModel.showEvents.value;
  const meta = showModel.showMeta.value;

  return (
    <Box boxSize="full" p={4}>
      <VStack gap={4} align="stretch">
        <Box>
          <HStack justify="space-between" mb={2}>
            <Heading size="md">Show Details</Heading>
            <Button
              size="sm"
              variant="outline"
              onClick={() =>
                void floatingPanelModel.openFloatingPanel(
                  FloatingPanelType.InspectShow,
                  "Inspect show",
                )
              }
            >
              Inspect
            </Button>
          </HStack>
        </Box>

        <VStack gap={2} align="stretch">
          <Box>
            <Text fontSize="sm" color="fg.muted">
              Mode
            </Text>
            <Text fontFamily="mono" fontSize="md">
              {mode === ShowMode.EDITING ? "Editing" : mode === ShowMode.LIVE ? "Live" : "Unknown"}
            </Text>
          </Box>

          {Object.keys(events).length > 0 && (
            <Box>
              <Text fontSize="sm" color="fg.muted">
                Timeline
              </Text>
              <Text fontFamily="mono" fontSize="md">
                {Object.keys(events).length} event{Object.keys(events).length !== 1 ? "s" : ""} |{" "}
                {showModel.showOrderedIds.value.length} ordered
              </Text>
            </Box>
          )}

          {meta && (
            <Box>
              <Text fontSize="sm" color="fg.muted">
                Metadata
              </Text>
              <Code display="block" whiteSpace="pre-wrap" p={2}>
                {JSON.stringify(meta, null, 2)}
              </Code>
            </Box>
          )}

          <Box>
            <Text fontSize="sm" color="fg.muted">
              Version
            </Text>
            <Text fontFamily="mono" fontSize="md">
              {showModel.dataVersion.value}
            </Text>
          </Box>
        </VStack>
      </VStack>
    </Box>
  );
}
