// apps/web-vue/src/features/control/panels/main/tabs/cue-item.vue
<script setup lang="ts">
import { Box, VStack } from "@styled-system/jsx";

import { CUE_CONFIG, type Cue } from "./cue";

defineOptions({ name: "CueItem" });
const props = defineProps<{ cue: Cue }>();
</script>

<template>
  <VStack gap="4" alignItems="start">
    <Box :fontSize="CUE_CONFIG[props.cue].headingSize" fontWeight="bold">
      {{ CUE_CONFIG[props.cue].label }}
    </Box>
    <Box
      as="span"
      :fontSize="CUE_CONFIG[props.cue].contentSize"
      fontFamily="mono"
      textTransform="uppercase"
      overflowWrap="break-word"
      lineHeight="1.6"
    >
      <slot />
    </Box>
  </VStack>
</template>

// apps/web/src/features/control/panels/main/tabs/cue-item.tsx
import { Text, type TextProps, VStack } from "@chakra-ui/react";
import type { ReactNode } from "react";

import { Heading } from "@/features/shared/ui/heading";

export enum Cue {
  CURRENT,
  NEXT,
  PREVIOUS,
}

const CUE_CONFIG: Record<
  Cue,
  { label: string; headingSize: TextProps["fontSize"]; contentSize: TextProps["fontSize"] }
> = {
  [Cue.CURRENT]: { label: "Current", headingSize: "3xl", contentSize: "2xl" },
  [Cue.NEXT]: { label: "Next", headingSize: "2xl", contentSize: "xl" },
  [Cue.PREVIOUS]: { label: "Previous", headingSize: "xl", contentSize: "lg" },
};

interface CueItemProps {
  cue: Cue;
  children: ReactNode;
}

export function CueItem({ cue, children }: CueItemProps) {
  const config = CUE_CONFIG[cue];

  return (
    <VStack gap={4} alignItems="start">
      <Heading fontSize={config.headingSize}>{config.label}</Heading>
      <Text
        as="span"
        fontSize={config.contentSize}
        fontFamily="mono"
        textTransform="uppercase"
        overflowWrap="break-word"
        lineHeight="1.6"
      >
        {children}
      </Text>
    </VStack>
  );
}

export { CUE_CONFIG };
