// apps/web-vue/src/features/leaderboard/leaderboard-table.vue
<script setup lang="ts">
import { table } from "@styled-system/recipes";
import type { ProblemDefinition } from "@tgb-resolver/realtime";

defineOptions({ name: "LeaderboardTable" });
defineProps<{ problems?: ProblemDefinition[] }>();
const classes = table({ size: "md", variant: "line", stickyHeader: true });
</script>
<template><table :class="classes.root"><thead :class="classes.header"><tr :class="classes.row"><th :class="classes.columnHeader">Rank</th><th :class="classes.columnHeader">User</th><th v-for="problem in problems" :key="problem.id" :class="classes.columnHeader">{{ problem.label }}</th><th :class="classes.columnHeader">Score</th><th :class="classes.columnHeader">Penalty</th><th :class="classes.columnHeader">Time</th></tr></thead><tbody :class="classes.body"><slot /></tbody></table></template>

// apps/web/src/components/resolve/leaderboard-table.tsx
import { Table } from "@chakra-ui/react";
import type { ProblemDefinition } from "@tgb-resolver/realtime";
import type { FC, ReactNode } from "react";

interface LeaderboardTableProps {
  problems: ProblemDefinition[] | undefined;
  children: ReactNode;
}

const LeaderboardTable: FC<LeaderboardTableProps> = ({ problems, children }) => {
  return (
    <Table.Root size="sm">
      <Table.Header>
        <Table.Row>
          <Table.ColumnHeader>Rank</Table.ColumnHeader>
          <Table.ColumnHeader>User</Table.ColumnHeader>

          {problems?.map((problem) => (
            <Table.ColumnHeader key={problem.id}>{problem.label}</Table.ColumnHeader>
          ))}

          <Table.ColumnHeader>Score</Table.ColumnHeader>
          <Table.ColumnHeader>Penalty</Table.ColumnHeader>
        </Table.Row>
      </Table.Header>

      <Table.Body>{children}</Table.Body>
    </Table.Root>
  );
};

export default LeaderboardTable;
