// apps/web-vue/src/features/leaderboard/leaderboard-row.vue
<script setup lang="ts">
import { VerdictRunResult } from "@tgb-resolver/contracts";
import type { LeaderboardEntry } from "@tgb-resolver/realtime";
import { computed } from "vue";

defineOptions({ name: "LeaderboardRow" });
const props = defineProps<{ data: LeaderboardEntry; isCurrentResolved: boolean }>();
const time = computed(() => { const total = Math.floor(Math.max(...props.data.problems.map((problem) => problem.timeSinceStart), props.data.lastSubmittedSeconds ?? 0, 0)); return `${Math.floor(total / 3600)}:${String(Math.floor(total / 60) % 60).padStart(2, "0")}:${String(total % 60).padStart(2, "0")}`; });
function score(problem: LeaderboardEntry["problems"][number]) { return problem.verdict === VerdictRunResult.UNKNOWN ? " " : problem.score; }
</script>
<template><tr :data-current="isCurrentResolved || undefined"><td>{{ data.rank }}</td><td><strong>{{ data.realName }}</strong><em>{{ data.username }}</em></td><td v-for="problem in data.problems" :key="problem.problemId"><span>{{ score(problem) }}</span><small>{{ problem.verdict }}</small></td><td>{{ data.totalScore }}</td><td>{{ data.totalPenalty }}</td><td>{{ time }}</td></tr></template>

// apps/web/src/components/resolve/leaderboard-row.tsx
import { Table } from "@chakra-ui/react";
import type { LeaderboardEntry } from "@tgb-resolver/realtime";
import type { FC } from "react";

interface LeaderboardRowProps {
  data: LeaderboardEntry;
}

const LeaderboardRow: FC<LeaderboardRowProps> = ({ data }) => {
  const username = `${data.realName} (${data.username})`;
  return (
    <Table.Row>
      <Table.Cell>{data.rank}</Table.Cell>
      <Table.Cell>{username}</Table.Cell>
      {data.problems.map((problem) => (
        <Table.Cell key={problem.problemId}>{problem.score}</Table.Cell>
      ))}
      <Table.Cell>{data.totalScore}</Table.Cell>
      <Table.Cell>{data.totalPenalty}</Table.Cell>
    </Table.Row>
  );
};

export default LeaderboardRow;
