// apps/web/src/features/shared/app/error-page.tsx
import { Button, Code, Icon, Stack, Text, VStack } from "@chakra-ui/react";
import { useSignal } from "@preact/signals-react";
import { Copy } from "lucide-react";

export function NotFoundPage() {
  return (
    <VStack minH="100dvh" align="center" justify="center" gap={2} bg="bg.subtle">
      <Text fontSize="lg" fontWeight="medium" color="fg">
        404{" "}
        <Text as="span" color="fg.muted" mx={2}>
          |
        </Text>{" "}
        Not found
      </Text>

      <Text fontSize="sm" color="fg.muted">
        This page is not available or does not exist. Please check the URL or return to the
        homepage.
      </Text>
    </VStack>
  );
}

export function ErrorPage({ error }: { error: Error }) {
  const isCopied = useSignal(false);

  const handleCopyError = () => {
    const errorData = {
      name: error.name,
      message: error.message,
      stack: error.stack,
    };
    navigator.clipboard.writeText(JSON.stringify(errorData, null, 2));
    isCopied.value = true;
    setTimeout(() => (isCopied.value = false), 2000);
  };

  return (
    <VStack minH="100dvh" align="center" justify="center" bg="bg.subtle" p={6}>
      <Stack
        w="full"
        maxW="4xl"
        gap={4}
        rounded="md"
        bg="bg.panel"
        p={6}
        shadow="md"
        borderWidth={1}
        borderColor="border.error"
      >
        <Stack gap={1}>
          <Text fontSize="lg" fontWeight="medium" color="fg.error">
            Error
          </Text>
          <Text fontSize="sm" color="fg.muted">
            Please retry or contact support if the issue persists. You can copy the error details
            below for reference.
          </Text>
        </Stack>

        <Stack gap={2}>
          <Button
            size="xs"
            colorPalette="gray"
            variant="surface"
            onClick={handleCopyError}
            w="fit-content"
          >
            <Icon as={Copy} w={3} h={3} mr={1} />
            {isCopied.value ? "Copied" : "Copy Error"}
          </Button>

          <Text fontSize="sm" fontWeight="bold" color="fg">
            {error.name}
          </Text>
          <Code p={3} whiteSpace="pre-wrap" display="block">
            {error.message}
          </Code>
          {error.stack ? (
            <Code p={3} whiteSpace="pre-wrap" display="block" fontSize="xs">
              {error.stack}
            </Code>
          ) : null}
        </Stack>
      </Stack>
    </VStack>
  );
}

// apps/web-vue/src/features/shared/app/error-page.vue
<script setup lang="ts">
import { Copy } from "@lucide/vue";
import { Box, Stack, VStack } from "@styled-system/jsx";
import { ref } from "vue";

defineOptions({ name: "ErrorPage" });

const props = defineProps<{ error: Error }>();

const isCopied = ref(false);

function handleCopyError() {
  const errorData = {
    name: props.error.name,
    message: props.error.message,
    stack: props.error.stack,
  };
  void navigator.clipboard.writeText(JSON.stringify(errorData, null, 2));
  isCopied.value = true;
  setTimeout(() => (isCopied.value = false), 2000);
}
</script>

<template>
  <VStack minH="100dvh" justify="center" bg="bg.subtle" p="6">
    <Stack w="full" maxW="4xl" gap="4" rounded="md" bg="bg.panel" p="6" shadow="md" borderWidth="1" borderColor="border.error">
      <Stack gap="1">
        <Box fontSize="lg" fontWeight="medium" color="fg.error">
          Error
        </Box>
        <Box fontSize="sm" color="fg.muted">
          Please retry or contact support if the issue persists. You can copy the error details
          below for reference.
        </Box>
      </Stack>

      <Stack gap="2">
        <button type="button" class="_copy" @click="handleCopyError">
          <Copy class="_copy-icon" aria-hidden />
          {{ isCopied ? "Copied" : "Copy Error" }}
        </button>

        <Box fontSize="sm" fontWeight="bold" color="fg">
          {{ error.name }}
        </Box>
        <pre class="_stack">{{ error.message }}</pre>
        <pre v-if="error.stack" class="_stack _stack-xs">{{ error.stack }}</pre>
      </Stack>
    </Stack>
  </VStack>
</template>

<style scoped>
._copy {
  display: inline-flex;
  align-items: center;
  gap: 0.25rem;
  width: fit-content;
  padding: 0.125rem 0.5rem;
  border: 1px solid var(--colors-border-muted);
  border-radius: var(--radii-sm);
  background: var(--colors-bg-subtle);
  color: var(--colors-fg);
  font-size: 0.75rem;
  cursor: pointer;
  transition: background 0.15s ease;
}

._copy:hover {
  background: var(--colors-bg-muted);
}

._copy-icon {
  width: 0.75rem;
  height: 0.75rem;
}

._stack {
  margin: 0;
  padding: 0.75rem;
  border: 1px solid var(--colors-border-muted);
  border-radius: var(--radii-sm);
  background: var(--colors-bg-subtle);
  font-family: var(--fonts-mono);
  font-size: 0.875rem;
  white-space: pre-wrap;
  overflow-wrap: anywhere;
  overflow: auto;
  max-height: 24rem;
}

._stack-xs {
  font-size: 0.75rem;
  max-height: 16rem;
}
</style>
