// apps/web/src/features/extensions/config-panel.tsx
import { Button, EmptyState, HStack, Stack, Text } from "@chakra-ui/react";
import { useSignal } from "@preact/signals-react";
import { useForm, useStore } from "@tanstack/react-form";
import { getDefaultValues, type RuntimeFormDefinition, toValibotSchema } from "@tgb-form/core";
import { TgbForm } from "@tgb-form/react";
import { type TimelineEvent, TimelineEventType } from "@tgb-resolver/realtime";
import { useEffect, useMemo } from "react";

import type { FloatingPanelHandle } from "@/features/control/floating-panel-model";
import { showModel } from "@/features/shared/show-model";

import { extensionRegistry } from "./base/registry";
import { usePatchExtensionPayload } from "./patch";
import { sharedRendererRegistry } from "./renderers";

type CustomTimelineEvent = Extract<TimelineEvent, { type: TimelineEventType.CUS }>;

interface ExtensionConfigPanelProps {
  panel: FloatingPanelHandle;
  eventId: number;
}

export function ExtensionConfigPanel({ panel, eventId }: ExtensionConfigPanelProps) {
  const event = showModel.showEvents.value[eventId];

  if (!event || event.type !== TimelineEventType.CUS) {
    return (
      <EmptyState.Root>
        <EmptyState.Content>
          <EmptyState.Title>No configuration available</EmptyState.Title>
          <EmptyState.Description>This event has no extension config.</EmptyState.Description>
        </EmptyState.Content>
      </EmptyState.Root>
    );
  }

  const ext = extensionRegistry.extensionWithExtId(event.payload.extId);
  const configForm = ext?.configForm;

  if (!configForm) {
    return (
      <EmptyState.Root>
        <EmptyState.Content>
          <EmptyState.Title>No configuration available</EmptyState.Title>
          <EmptyState.Description>
            Extension "{event.payload.extId}" has no config form.
          </EmptyState.Description>
        </EmptyState.Content>
      </EmptyState.Root>
    );
  }

  return (
    <ExtensionConfigForm panel={panel} event={event} eventId={eventId} configForm={configForm} />
  );
}

function ExtensionConfigForm({
  panel,
  event,
  eventId,
  configForm,
}: {
  panel: FloatingPanelHandle;
  event: CustomTimelineEvent;
  eventId: number;
  configForm: RuntimeFormDefinition;
}) {
  const patchPayload = usePatchExtensionPayload();
  const error = useSignal<string | null>(null);

  const baseline = useMemo(
    () =>
      ({ ...getDefaultValues(configForm), ...event.payload.extPayload }) as Record<string, unknown>,
    [configForm, event],
  );

  const form = useForm({
    defaultValues: baseline,
    validators: {
      onSubmit: toValibotSchema(configForm) as never,
    },
    onSubmit: async ({ value }) => {
      error.value = null;
      panel.setSaving(true);
      try {
        await patchPayload(eventId, event.payload.extId, value);
        panel.close(true);
      } catch (err) {
        error.value = err instanceof Error ? err.message : String(err);
      } finally {
        panel.setSaving(false);
      }
    },
  });

  const isDirty = useStore(
    form.store,
    (state) => JSON.stringify(state.values) !== JSON.stringify(baseline),
  );
  const canSubmit = useStore(form.store, (state) => state.canSubmit);

  useEffect(() => {
    panel.setDirty(isDirty);
  }, [isDirty, panel]);

  return (
    <Stack gap={4} h="full">
      <TgbForm
        definition={configForm}
        instance={form as unknown as Record<string, unknown>}
        renderers={sharedRendererRegistry}
      />
      <HStack justify="end">
        <Button variant="outline" onClick={() => void panel.requestClose()}>
          Cancel
        </Button>
        <Button
          disabled={!canSubmit || !isDirty || panel.isSaving.value}
          onClick={() => void form.handleSubmit()}
        >
          Save
        </Button>
      </HStack>
      {error.value && (
        <Text color="fg.error" fontSize="sm">
          {error.value}
        </Text>
      )}
    </Stack>
  );
}

// apps/web-vue/src/features/extensions/config-panel.vue
<script setup lang="ts">
import { css } from "@styled-system/css";
import { TgbForm } from "@tgb-form/vue";
import { computed, ref, watch } from "vue";

import type { FloatingPanelHandle } from "@/features/control/floating-panel-types";
import Button from "@/features/shared/ui/button.vue";

import { patchExtensionEvent } from "./patch";
import { useExtensionRegistry } from "./registry";
import { extensionRendererRegistry } from "./renderers";
import { computeScrollerExtensionDuration } from "./scroller/duration";
import { createTgbFormInstance } from "./tgb-form-instance";

const props = defineProps<{ panel: FloatingPanelHandle }>();

const registry = useExtensionRegistry();

const params = computed(
  () =>
    props.panel.props.value as {
      eventId?: number;
      extId?: string;
      payload?: Record<string, unknown>;
    },
);

const extension = computed(() => registry.extensionWithExtId(params.value.extId ?? ""));
const baseline = computed(() => params.value.payload ?? {});
const instance = createTgbFormInstance(baseline.value);
const saving = ref(false);
const error = ref<string | null>(null);

watch(
  () => JSON.stringify(instance.values),
  (current, previous) => {
    if (previous === undefined) return;
    props.panel.setDirty(current !== JSON.stringify(baseline.value));
  },
  { immediate: true },
);

async function save() {
  const eventId = params.value.eventId;
  const extId = params.value.extId;
  if (eventId == null || !extId) {
    props.panel.close(true);
    return;
  }
  saving.value = true;
  error.value = null;
  try {
    const duration =
      extId === "scroller" ? computeScrollerExtensionDuration(instance.values) : undefined;
    await patchExtensionEvent(eventId, extId, instance.values, duration);
    props.panel.close(true);
  } catch (cause) {
    error.value = cause instanceof Error ? cause.message : String(cause);
  } finally {
    saving.value = false;
  }
}

function cancel() {
  void props.panel.requestClose();
}
</script>

<template>
  <div :class="css({ display: 'flex', flexDirection: 'column', gap: 4, h: 'full' })">
    <p :class="css({ color: 'fg.muted', fontSize: 'sm' })">
      {{ extension?.description ?? 'Extension configuration' }}
    </p>
    <TgbForm
      v-if="extension?.configForm"
      :definition="extension.configForm"
      :instance="instance.values"
      :renderers="extensionRendererRegistry"
    />
    <p v-if="error" :class="css({ color: 'fg.error', fontSize: 'sm' })">{{ error }}</p>
    <div :class="css({ display: 'flex', justifyContent: 'flex-end', gap: 2 })">
      <Button variant="outline" :disabled="saving" @click="cancel">Cancel</Button>
      <Button :loading="saving" @click="save">Save</Button>
    </div>
  </div>
</template>
